-- Data-integrity fix: no post should show more comments/shares/saves
-- than likes. Tops up post_likes from the seeded fake-profile pool
-- (never deletes real comment/save content) and caps share_count down
-- to <= the resulting like count. Deterministic (random.seed(42)),
-- generated by scratchpad/gen_engagement_fix.py, run once.

insert into public.post_likes (post_id, user_id) values
  ('a41a0775-a279-434b-b550-69ed98a5095b', '4dd97921-6049-4bf4-b82c-4b5bf4147f34'),
  ('133778c4-4045-4e24-96b8-824bc6fd2372', '8b7fa4ae-40e2-4a93-b97b-39f0e6681435'),
  ('133778c4-4045-4e24-96b8-824bc6fd2372', '0c748e96-12e0-42b4-9964-1de95f4597d6'),
  ('133778c4-4045-4e24-96b8-824bc6fd2372', '5c39d7c4-b54f-4afa-9198-b2aceb8c1bd9'),
  ('133778c4-4045-4e24-96b8-824bc6fd2372', 'f423eca9-15ef-4a5c-b026-acd764ac59de'),
  ('133778c4-4045-4e24-96b8-824bc6fd2372', '322afa8e-2996-4069-a4e4-f14aab0a1749'),
  ('5912ceee-db62-4039-ac31-d8caa1e31b96', '8fda1fce-f1c0-489f-8407-d8fede14b5db'),
  ('5912ceee-db62-4039-ac31-d8caa1e31b96', 'f0fef89e-6517-447a-ad46-df5b5c5df628'),
  ('2d09ab85-9c9f-4bd4-b71a-622f41d1bbf8', '7b503c95-9ac1-40f9-8d2a-08ed9beda083'),
  ('2d09ab85-9c9f-4bd4-b71a-622f41d1bbf8', 'f15e3325-185a-48ef-9813-8ee0ec981937'),
  ('3446f8c1-07ce-476e-a81c-cf946c8f2b76', 'f0d0bbb6-5462-4556-9459-c9244bbeb39a'),
  ('3446f8c1-07ce-476e-a81c-cf946c8f2b76', '1c64a0ba-3d9b-4d57-8e0a-af3c25c40804'),
  ('e1218998-0a72-4963-acb3-e21c5b93f0c5', 'f78f4295-3c87-42ff-806b-9f6c791ef7ea'),
  ('e1218998-0a72-4963-acb3-e21c5b93f0c5', '214c2e67-4c09-4e8d-b4c5-616a4d574cb4'),
  ('746b9ef6-1d9b-4cde-99fb-f26e84b1414e', 'fd7b7917-bfcd-49c2-aec3-5396a1152134'),
  ('746b9ef6-1d9b-4cde-99fb-f26e84b1414e', '10e20f32-2b4b-435d-953f-6b512b4b047f'),
  ('746b9ef6-1d9b-4cde-99fb-f26e84b1414e', '55e2886d-9703-4678-b296-3830add9dc4a'),
  ('462d91b2-c9f2-42cc-b028-3060b0252b59', '81e6ca88-c7c8-4473-b5d3-c6da54c9a0cf'),
  ('462d91b2-c9f2-42cc-b028-3060b0252b59', '8fda1fce-f1c0-489f-8407-d8fede14b5db'),
  ('04712a4b-9e0a-4109-82a0-14d2c06ec732', '21bd5c08-3c05-4c9e-aacc-49ca4c672de7'),
  ('04712a4b-9e0a-4109-82a0-14d2c06ec732', '51101589-0384-4265-b9ef-3cf2d3de1cfb'),
  ('04712a4b-9e0a-4109-82a0-14d2c06ec732', 'c483b92f-4f2b-4a6b-b1c0-4ac828513aeb'),
  ('04712a4b-9e0a-4109-82a0-14d2c06ec732', '8725f518-ba57-45fa-96f4-6c2edb3b7705'),
  ('04712a4b-9e0a-4109-82a0-14d2c06ec732', '469dd7c8-3bc3-4535-a661-a4bd6bb7d4e0'),
  ('91191959-faec-452b-986a-00262509b2af', '898cb3e2-d007-4d7e-99b0-b1f8b199cc2d'),
  ('48ea8ba3-2c92-4e08-8c5f-8fdd0accd63a', 'd7d3471b-8e70-4a4c-a05a-a5387be207fc'),
  ('ac2d60b5-dcf4-4df0-9c32-e34029820b91', 'be2fb8e8-f990-43a0-9e4c-a2c6afdcd663'),
  ('ac2d60b5-dcf4-4df0-9c32-e34029820b91', '030d26d4-571a-4cb2-ab98-e72c6fd3720c'),
  ('4ac0fd43-84d7-46bc-b94f-9a00f8e0b36c', '7e9dd57b-ce06-4b8c-bbfb-34be668c202e'),
  ('14d929ba-eada-47d8-9257-93eb430659a7', '7054f64a-0718-43a1-888f-a9d8e2ac1bbb'),
  ('14d929ba-eada-47d8-9257-93eb430659a7', '322afa8e-2996-4069-a4e4-f14aab0a1749'),
  ('14d929ba-eada-47d8-9257-93eb430659a7', '58176b34-cbf6-4253-8497-7dc4e4746a4e'),
  ('14d929ba-eada-47d8-9257-93eb430659a7', 'fafceac2-d255-4289-a794-090d087b8c1f'),
  ('14d929ba-eada-47d8-9257-93eb430659a7', '1e30a9fe-0a29-49cb-b9cb-ab8430f7f055'),
  ('59f71b8a-2447-48d9-882a-01589b5ae528', '31d1c596-c131-41d9-92bf-6e68367e6f5e'),
  ('59f71b8a-2447-48d9-882a-01589b5ae528', '3629b2c1-f1c7-47db-a68f-447929f52d74'),
  ('59f71b8a-2447-48d9-882a-01589b5ae528', '258916f4-4c1f-4c49-b367-55748140a23e'),
  ('59f71b8a-2447-48d9-882a-01589b5ae528', '7d4aae4f-2bc6-4660-b841-694bb489ec72'),
  ('59f71b8a-2447-48d9-882a-01589b5ae528', 'efba2439-7b38-450b-9472-bc308bb3e9ce');

update public.posts set share_count = 13 where id = '50835035-314e-42f5-82e3-ed84dfdf46aa';
update public.posts set share_count = 16 where id = 'b7c1d201-09c1-40ad-8915-b23a546258b2';
update public.posts set share_count = 39 where id = 'f858db08-266b-456c-9d7d-f48228072eaa';
update public.posts set share_count = 10 where id = 'd915836a-c221-4cdf-9b39-bcf3d90bec63';
update public.posts set share_count = 19 where id = '1f47e8f0-0e5f-4ee5-a449-fc73b6ae96b7';
update public.posts set share_count = 3 where id = 'a41a0775-a279-434b-b550-69ed98a5095b';
update public.posts set share_count = 14 where id = '9769451a-370b-46d4-ad18-c579659a46c7';
update public.posts set share_count = 3 where id = '116b3f4a-00ad-42b6-b698-8caf32ee00a2';
update public.posts set share_count = 3 where id = 'a144ba0b-dee3-4d2d-b68b-c5cd3271b7fa';
update public.posts set share_count = 18 where id = '85ddf78a-ddc8-4f84-808d-b05c44770f0b';
update public.posts set share_count = 1 where id = '20b7023f-d02a-4937-bc5f-4669c071bcb9';
update public.posts set share_count = 5 where id = '5912ceee-db62-4039-ac31-d8caa1e31b96';
update public.posts set share_count = 5 where id = '2d09ab85-9c9f-4bd4-b71a-622f41d1bbf8';
update public.posts set share_count = 3 where id = '018c4c43-b0d3-41a6-b9db-72a6a90e3af6';
update public.posts set share_count = 10 where id = 'fa4a6a0b-b4d8-4c3e-ac94-a273690f8c42';
update public.posts set share_count = 10 where id = '8790b051-0b04-482e-a9bc-319c98ed0969';
update public.posts set share_count = 11 where id = 'f249ddef-52ca-4566-b094-add6cd0e344d';
update public.posts set share_count = 3 where id = '746b9ef6-1d9b-4cde-99fb-f26e84b1414e';
update public.posts set share_count = 3 where id = '94d0def4-3306-4b55-a31f-83e1fac495b8';
update public.posts set share_count = 3 where id = 'ea1610fc-03b3-452f-a0c6-0515f388d307';
update public.posts set share_count = 16 where id = '74f35424-a33e-4e58-8922-b0a2fa3d98ab';
update public.posts set share_count = 1 where id = 'af6a434f-99e3-4b77-ad80-2564a0818220';
update public.posts set share_count = 2 where id = 'fbb86f10-db58-4e5d-a567-95b1edf0b79f';
update public.posts set share_count = 5 where id = '462d91b2-c9f2-42cc-b028-3060b0252b59';
update public.posts set share_count = 1 where id = '56720360-a1b9-4251-854e-8f46778ffe9d';
update public.posts set share_count = 4 where id = '04712a4b-9e0a-4109-82a0-14d2c06ec732';
update public.posts set share_count = 2 where id = '75d82852-d10b-4fe6-97c0-14dd9db2bd7f';
update public.posts set share_count = 9 where id = 'ecdab528-ff0f-458b-a3ad-dc5a5c65c924';
update public.posts set share_count = 7 where id = '91191959-faec-452b-986a-00262509b2af';
update public.posts set share_count = 9 where id = 'd1e7dd97-1c00-4a97-b53a-c101585030eb';
update public.posts set share_count = 8 where id = '48ea8ba3-2c92-4e08-8c5f-8fdd0accd63a';
update public.posts set share_count = 9 where id = 'ac2d60b5-dcf4-4df0-9c32-e34029820b91';
update public.posts set share_count = 2 where id = 'a48532d4-f511-425c-a710-ab61a5ec0406';
update public.posts set share_count = 15 where id = 'a58271e5-3607-44ec-8314-ccf2670ab030';
update public.posts set share_count = 34 where id = '65d2cf69-20d4-4f5a-86cb-ccfb7f89b3d2';
update public.posts set share_count = 5 where id = '2ec343c9-14bd-4b54-a052-ac421006317f';
update public.posts set share_count = 3 where id = 'dcd8abf4-a962-462d-a3e8-414f809473ee';
update public.posts set share_count = 4 where id = '85475dbf-5e6d-433a-bb14-d04e7f2b6ef7';
update public.posts set share_count = 37 where id = 'add2f40d-c828-4363-917f-ecbc0803aa46';
update public.posts set share_count = 11 where id = '7d2415ad-7aff-4eca-bff7-6b8fb8374a0e';
update public.posts set share_count = 6 where id = 'df51b69f-5626-445b-94b8-3933ae5cecd0';
update public.posts set share_count = 6 where id = 'ef7493d0-63f6-42d3-a60c-f997b47a7b12';
update public.posts set share_count = 2 where id = 'fa723721-1e30-40ac-a843-9a7527944385';
update public.posts set share_count = 10 where id = '0dddc40e-5309-46e0-9014-54a779f0b11d';
update public.posts set share_count = 2 where id = '6c36f98e-3df9-4222-baac-f4a14135a4e6';
update public.posts set share_count = 15 where id = '52b9f160-f844-4922-837b-59b7fdfd87cb';
update public.posts set share_count = 13 where id = '73489cef-6192-4ba8-813b-5e71fd709f28';
update public.posts set share_count = 2 where id = '4ac0fd43-84d7-46bc-b94f-9a00f8e0b36c';
update public.posts set share_count = 1 where id = 'def6ebe0-927d-411b-9ee4-07e0cb65208b';
update public.posts set share_count = 9 where id = '00390065-450c-4fbc-9178-df550ac7aefb';
update public.posts set share_count = 28 where id = '8696f82d-011b-46c4-8165-647435d27eae';
update public.posts set share_count = 7 where id = '14d929ba-eada-47d8-9257-93eb430659a7';
update public.posts set share_count = 18 where id = 'fc08ae9f-4fbd-4154-8304-22d65f4f9f93';
update public.posts set share_count = 25 where id = 'ccdc53f7-6d6f-408e-841b-f704bd8e49ac';
update public.posts set share_count = 4 where id = 'fc14722a-1567-4a49-aba7-5d646d9af957';
update public.posts set share_count = 21 where id = '65daf5a3-e84a-47c0-bf48-84d9112a465b';
update public.posts set share_count = 10 where id = '78392cbf-a12a-4f7d-bef3-18205aae024f';
update public.posts set share_count = 12 where id = 'ea06cb38-a692-4b7d-9afa-469910e702d5';
update public.posts set share_count = 11 where id = '72188c97-a4e0-4737-bf52-a8894737aed3';
update public.posts set share_count = 13 where id = '3f5e574f-0d2b-4857-a680-ef9213b1b9d8';
update public.posts set share_count = 2 where id = '46f26ae5-3b6e-4c85-84cd-409e2c02c9c3';
update public.posts set share_count = 8 where id = '9880a0c6-37e2-436d-b1d5-0f88a1581f6a';
update public.posts set share_count = 2 where id = '4ee392ec-429b-4bdc-9bae-ef57a6189e2f';
update public.posts set share_count = 19 where id = '28006930-f156-47a1-97e5-5ca505bce03b';
update public.posts set share_count = 10 where id = '30d58e61-88b9-41ee-8dc9-a261e6ead75e';
update public.posts set share_count = 10 where id = '37cdcaca-095a-4f3b-8198-15168cfcd7af';
update public.posts set share_count = 3 where id = 'c8accce3-ad2e-4ece-bedd-7006739a6bb9';
