-- Backfills recipe_text for the 101 official recipe-catalog posts
-- (author_id is null, recipe_id set) from recipes.json's own `steps` —
-- real app content, not AI-generated, so recipe_is_ai_generated stays false.
-- Generated by scratchpad/gen_official_recipe_sql.mjs, run once.

update public.posts set recipe_text = '1. Mercimekleri yıkayın ve sebzeleri doğrayın.
2. Soğan ve havucu tereyağında yumuşayana kadar kavurun, salçayı ekleyip karıştırın.
3. Mercimek, patates ve suyu ekleyip yumuşayana kadar 20 dakika pişirin.
4. Pürüzsüz olana kadar blenderdan geçirin, kimyonla tatlandırıp limonla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_001';
update public.posts set recipe_text = '1. Doğranmış soğanı tereyağında pembeleşene kadar kavurun.
2. Salçayı ekleyin, ardından mercimek, bulgur ve pirinci suyla birlikte ekleyin.
3. Her şey yumuşayana kadar ara ara karıştırarak 30 dakika pişirin.
4. Servis etmeden önce eritilmiş tereyağı, nane ve pul biberle süsleyin.', recipe_is_ai_generated = false where recipe_id = 'recipe_002';
update public.posts set recipe_text = '1. Pirinci suda yumuşayana kadar haşlayın.
2. Yoğurt, un ve yumurtayı çırpın, sıcak suyla temperleyin.
3. Yoğurt karışımını tencereye ekleyip kaynatmadan hafifçe pişirin.
4. Üzerine nane ile eritilmiş tereyağı gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_003';
update public.posts set recipe_text = '1. Patlıcanları yumuşayana kadar kızartın, sonra uzunlamasına yarın.
2. Kıymayı soğan, biber ve sarımsakla kahverengileşene kadar pişirin.
3. Domates ve salçayı ekleyip koyu bir iç harç oluşana kadar pişirin.
4. Patlıcanları doldurun, üzerine domates dilimi koyup fırınlayın.', recipe_is_ai_generated = false where recipe_id = 'recipe_004';
update public.posts set recipe_text = '1. Fasulyeleri bir gece suda bekletin, sonra yumuşayana kadar haşlayın.
2. Soğan ve sucuğu yağda kavurun, salçayı ekleyin.
3. Fasulyeleri haşlama suyuyla birlikte ekleyip 30 dakika pişirin.
4. Pul biberle tatlandırıp pilavla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_005';
update public.posts set recipe_text = '1. Pirinci iyice yıkayıp kısa süre bekletin.
2. Soğanı tereyağında altın rengi olana kadar kavurun, süzülmüş nohutu ekleyin.
3. Pirinci ekleyip 2 dakika kavurun, ardından sıcak su ekleyin.
4. Kapağını kapatıp pirinç yumuşayana kadar pişirin, demlendirip servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_006';
update public.posts set recipe_text = '1. Tavuğu zeytinyağı, limon suyu, sarımsak ve kırmızı toz biberle marine edin.
2. En az 20 dakika dinlendirin.
3. Orta-yüksek ateşte ızgarada veya tavada pişirin.
4. Dilimlemeden önce birkaç dakika dinlendirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_007';
update public.posts set recipe_text = '1. Tavuk butlarını küp küp doğrayıp baharatlayın.
2. Sıcak yağda altın rengi olana kadar mühürleyip kenara alın.
3. Soğan ve biberleri soteleyin, domatesi ekleyip pişirin.
4. Tavuğu tekrar tencereye ekleyip pişene kadar kısık ateşte pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_008';
update public.posts set recipe_text = '1. Kuzu kuşbaşıları zeytinyağında her tarafı kızarana kadar mühürleyin.
2. Soğan, sarımsak ve kimyonu ekleyip su ile kapatın.
3. Kapağı kapatıp et dağılana kadar kısık ateşte pişirin.
4. Sonunda kapağı açıp sosun biraz koyulaşmasını bekleyin.', recipe_is_ai_generated = false where recipe_id = 'recipe_009';
update public.posts set recipe_text = '1. Tüm sebzeleri iri parçalar halinde doğrayın.
2. Sebzeleri zeytinyağı ve sarımsakla birlikte bir tencereye ya da güveç kabına dizin.
3. Kapağını kapatıp ara sıra karıştırarak kısık ateşte sebzeler yumuşayana kadar pişirin.
4. Sıcak ya da oda sıcaklığında servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_010';
update public.posts set recipe_text = '1. Makarnayı tuzlu suda diri kalacak şekilde haşlayın.
2. Sarımsağı zeytinyağında soteleyip salça ve doğranmış domatesi ekleyin.
3. Sos kıvamına gelince süzülmüş makarnayla karıştırın.
4. Üzerine rendelenmiş kaşar peyniri serpip sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_011';
update public.posts set recipe_text = '1. Tavuk butlarını ve küp patatesleri zeytinyağı ve kırmızı toz biberle harmanlayın.
2. Fırın tepsisine tek sıra halinde dizin.
3. Yüksek ısıda, bir kez çevirerek altın rengi ve iyi pişene kadar fırınlayın.
4. Servis etmeden önce kısa süre dinlendirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_012';
update public.posts set recipe_text = '1. Domates, salatalık, biber ve soğanı küçük ve eşit parçalar halinde doğrayın.
2. Maydanozu ince kıyıp hepsini bir kapta birleştirin.
3. Zeytinyağı, limon suyu ve tuzla harmanlayın.
4. İyice karıştırıp hemen servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_013';
update public.posts set recipe_text = '1. Domates ve soğanı iri parçalar halinde doğrayın.
2. Cevizi ve maydanozu kabaca kıyın.
3. Hepsini zeytinyağı ve pul biberle birleştirin.
4. Hafifçe karıştırıp 5 dakika dinlendirdikten sonra servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_014';
update public.posts set recipe_text = '1. Mercimekleri yumuşayana kadar haşlayın, ocaktan alıp bulguru ekleyin ve demlendirin.
2. Soğanı salçayla birlikte zeytinyağında kokusu çıkana kadar soteleyin.
3. Mercimek-bulgur karışımına kimyon ve kıyılmış maydanozla birlikte ekleyin.
4. Küçük köfteler şekillendirip limon dilimleriyle servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_015';
update public.posts set recipe_text = '1. Haşlanmış nohutu tahin, limon suyu ve sarımsakla blenderdan geçirin.
2. Kıvam alana kadar yavaş yavaş soğuk su ekleyin.
3. Kimyon ve tuzla tatlandırın.
4. Bir tabağa yayıp üzerine zeytinyağı gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_016';
update public.posts set recipe_text = '1. Patlıcanları ateşte ya da fırında yumuşayana kadar közleyin.
2. İçini çıkarıp kısa süre süzülmeye bırakın.
3. Tahin, limon suyu ve sarımsakla ezin.
4. Servis etmeden önce zeytinyağı gezdirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_017';
update public.posts set recipe_text = '1. Salatalığı rendeleyin ya da küçük küpler halinde doğrayın.
2. Sarımsağı ezip dereotunu kıyın.
3. Hepsini bir tutam tuzla yoğurda karıştırın.
4. Zeytinyağı gezdirip servis etmeden önce soğutun.', recipe_is_ai_generated = false where recipe_id = 'recipe_018';
update public.posts set recipe_text = '1. Doğranmış yeşil biberi yağda yumuşayana kadar soteleyin.
2. Küp domatesi ekleyip sulu bir kıvama gelene kadar pişirin.
3. Yumurtaları kırıp hafifçe karıştırarak kıvamına gelene kadar pişirin.
4. Üzerine pul biber serpip tavadan sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_019';
update public.posts set recipe_text = '1. Sucuğu dilimleyip yağını bırakana kadar tavada kızartın.
2. Sucuğu bir kenara itip yumurtaları kırın.
3. Yumurtalar istediğiniz kıvama gelene kadar pişirin.
4. Sıcak olarak ekmekle servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_020';
update public.posts set recipe_text = '1. Yumurtaları bir tutam tuzla çırpın.
2. Tavada tereyağını eritip yumurtaları dökün.
3. Pişerken bir yarısına rendelenmiş peynir serpin.
4. Katlayıp peynir eriyene kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_021';
update public.posts set recipe_text = '1. Pirinci suda tamamen yumuşayana kadar kaynatın.
2. Süt, şeker ve vanilyayı ekleyip kıvam alana kadar pişirin.
3. Kaselere paylaştırıp üzeri hafif altın rengi olana kadar fırınlayın.
4. Servis etmeden önce soğutun.', recipe_is_ai_generated = false where recipe_id = 'recipe_022';
update public.posts set recipe_text = '1. Yumurtaları şekerin bir kısmıyla kabarana kadar çırpın, ardından yağ ve yoğurdu ekleyin.
2. İrmik, un ve kabartma tozunu ekleyip hamur kıvamına getirin.
3. Altın rengi alıp kürdan temiz çıkana kadar pişirin.
4. Sıcak keke soğumuş şerbeti gezdirip iyice çekmesini bekleyin.', recipe_is_ai_generated = false where recipe_id = 'recipe_023';
update public.posts set recipe_text = '1. Tereyağlı yufka katmanlarının arasına kıyılmış ceviz serperek dizin.
2. Fırınlamadan önce baklava dilimi şeklinde kesin.
3. Altın rengi ve çıtır olana kadar fırınlayın.
4. Sıcak baklavaya soğumuş limonlu şerbeti gezdirip iyice çekmesini bekleyin.', recipe_is_ai_generated = false where recipe_id = 'recipe_024';
update public.posts set recipe_text = '1. Unu bir miktar soğuk sütle pürüzsüz olana kadar karıştırın.
2. Kalan sütü şekerle ısıtın, ardından un karışımını ekleyin.
3. Sürekli karıştırarak kıvam alana kadar pişirin.
4. Kaselere paylaştırıp vanilya ekleyin ve servis etmeden önce soğutun.', recipe_is_ai_generated = false where recipe_id = 'recipe_025';
update public.posts set recipe_text = '1. Tarhanayı bir kaba alıp 1 su bardağı ılık suyla açın, pürüzsüz olana kadar karıştırın.
2. Tereyağını tencerede eritip salçayı ekleyip birkaç dakika kavurun.
3. Açılmış tarhanayı ve kalan suyu ekleyip karıştırarak orta ateşte 15-20 dakika, arada karıştırarak pişirin.
4. Pul biber ve nane ile tatlandırılmış tereyağını üzerinde gezdirerek sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_026';
update public.posts set recipe_text = '1. Soğanı tereyağında pembeleşene kadar kavurun.
2. Doğranmış patates ve brokoliyi ekleyip birkaç dakika soteleyin.
3. Üzerini geçecek kadar sıcak su ekleyip sebzeler yumuşayana kadar 15 dakika pişirin.
4. Sütü ekleyip blenderdan geçirin, karabiberle tatlandırıp sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_027';
update public.posts set recipe_text = '1. Bal kabağını kalın dilimler halinde kesip kabuğunu soyun.
2. Dilimleri bir tencereye dizip üzerine şekeri serpin, 1-2 saat dinlendirin.
3. Kendi suyunu salan kabakları kısık ateşte kabuğu şeffaflaşana ve şerbeti koyulaşana kadar pişirin.
4. Soğuduktan sonra üzerine dövülmüş ceviz ve tarçın serperek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_028';
update public.posts set recipe_text = '1. Mantarları temizleyip dilimleyin.
2. Tereyağını kızgın tavada eritip ezilmiş sarımsağı kısa süre kavurun.
3. Mantarları ekleyip suyunu salıp çekene kadar orta-yüksek ateşte pişirin.
4. Karabiber ekleyip doğranmış maydanozla süsleyerek sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_029';
update public.posts set recipe_text = '1. Tavuk göğsünü doğranmış soğan ve havuçla birlikte haşlayın, tavuğu didikleyin.
2. Süzülen suyu tencereye geri alıp kaynatın.
3. Şehriyeyi ekleyip yumuşayana kadar 8-10 dakika pişirin.
4. Didiklenmiş tavuğu geri ekleyip eritilmiş tereyağıyla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_030';
update public.posts set recipe_text = '1. Semizotunu ayıklayıp yıkayın ve iri doğrayın.
2. Zeytinyağında pirinci kısaca kavurup semizotunu ekleyin, kendi suyuyla yumuşayana kadar pişirin.
3. Yoğurdu ezilmiş sarımsakla karıştırın.
4. Soğuyan semizotunun üzerine sarımsaklı yoğurdu gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_031';
update public.posts set recipe_text = '1. Rokayı yıkayıp bir servis tabağına yayın.
2. Portakalın kabuğunu soyup ince dilimleyin, roka üzerine dizin.
3. Kabaca kırılmış cevizleri serpin.
4. Zeytinyağı ve limon suyunu karıştırıp salatanın üzerine gezdirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_032';
update public.posts set recipe_text = '1. Fırını 200°C''ye ısıtın, balık filetolarını fırın kağıdı serili tepsiye dizin.
2. Ezilmiş sarımsak, zeytinyağı ve limon suyunu karıştırıp filetoların üzerine gezdirin.
3. Fırında 15-18 dakika, balık kolayca dağılana kadar pişirin.
4. Doğranmış maydanoz ve limon dilimleriyle servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_033';
update public.posts set recipe_text = '1. Tereyağında ezilmiş sarımsağı kısaca kavurun, biber salçasını ekleyip karıştırın.
2. Rendelenmiş domatesleri ekleyip sos koyulaşana kadar pişirin.
3. Karidesleri ekleyip 3-4 dakika pişirin, güveç kaplarına paylaştırın.
4. Üzerine rendelenmiş kaşar serpip fırında peynir eriyene kadar pişirip sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_034';
update public.posts set recipe_text = '1. Bamyaların saplarını temizleyip limon suyuyla ovarak yıkayın.
2. Zeytinyağında soğanı pembeleşene kadar kavurun.
3. Rendelenmiş domatesi ve bamyaları ekleyip kısık ateşte 25-30 dakika pişirin.
4. Soğuk ya da ılık servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_035';
update public.posts set recipe_text = '1. Soğanı zeytinyağında kavurup pirinç, çam fıstığı ve baharatları ekleyip birkaç dakika kavurun.
2. Asma yapraklarını harçla doldurup sıkıca sarın.
3. Sarmaları tencereye sık dizip üzerine limon suyu ve su ilave edin.
4. Kısık ateşte 40-45 dakika pişirip soğuduktan sonra servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_036';
update public.posts set recipe_text = '1. Dana kuşbaşıyı yüksek ateşte kavurup rengi dönene kadar pişirin.
2. Salçayı ekleyip kısa süre kavurun, doğranmış domates ve sarımsağı ilave edin.
3. Üzerini geçecek kadar sıcak su ekleyip kapağı kapalı kısık ateşte 1 saat pişirin.
4. Doğranmış patates ve biberi ekleyip et ve sebzeler yumuşayana kadar 20 dakika daha pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_037';
update public.posts set recipe_text = '1. Fırını 200°C''ye ısıtın, ekmeği ortadan yarın.
2. Eritilmiş tereyağını ezilmiş sarımsakla karıştırıp ekmeğin iç yüzeyine sürün.
3. Üzerine rendelenmiş mozzarellayı eşit şekilde serpin.
4. Peynir eriyip hafif kızarana kadar fırınlayıp doğranmış maydanozla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_038';
update public.posts set recipe_text = '1. Kıymayı tuz ve karabiberle yoğurup 4 eşit köfte haline getirin, yassıltın.
2. Köfteleri yüksek ateşte her iki yüzünü mühürleyerek istenilen pişkinlikte pişirin, üzerine kaşar peynirini koyup eritin.
3. Ekmekleri hafifçe kızartın, iç yüzeylerine ketçap ve mayonez sürün.
4. Marul, domates ve köfteyi ekmeğin arasına yerleştirip servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_039';
update public.posts set recipe_text = '1. Lahana yapraklarını kaynar suda yumuşayana kadar haşlayıp süzün.
2. Kıyma, pirinç, rendelenmiş soğan ve salçayı yoğurup iç harcı hazırlayın.
3. Yaprakları harçla doldurup sıkıca sarın, tencereye dizin.
4. Üzerine sıcak su ilave edip kısık ateşte 45-50 dakika pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_040';
update public.posts set recipe_text = '1. Sütü tencerede kaynatmaya başlayın.
2. Yulafı ekleyip kısık ateşte karıştırarak 5-6 dakika pişirin.
3. Rendelenmiş elmayı ve tarçını ekleyip 2 dakika daha pişirin.
4. Sıcakken üzerine bal gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_041';
update public.posts set recipe_text = '1. Cezveye 1 fincan soğuk su, kahve ve istediğiniz kadar şekeri ekleyip karıştırın.
2. Kısık ateşte, karıştırmadan yavaşça ısıtın.
3. Köpük kabarmaya başlayınca ocaktan alıp köpüğü fincana paylaştırın.
4. Cezveyi ocağa geri koyup son kez kaynatıp fincana boşaltın, sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_042';
update public.posts set recipe_text = '1. Salep tozunu birkaç kaşık soğuk sütle pürüzsüz olana kadar karıştırın.
2. Kalan sütü ve şekeri tencerede ısıtın.
3. Salep karışımını ekleyip sürekli karıştırarak koyulaşana kadar kısık ateşte pişirin.
4. Bardaklara paylaştırıp üzerine tarçın serperek sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_043';
update public.posts set recipe_text = '1. İnce bulguru sıcak suda 15 dakika bekletip yumuşatın.
2. Salçaları, dövülmüş cevizi ve limon suyunu ekleyip uzun süre yoğurun.
3. Doğranmış maydanozu karıştırıp küçük parçalar halinde şekil verin.
4. Marul yaprağına sarıp soğuk bir bardak şalgamla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_044';
update public.posts set recipe_text = '1. Bitter çikolatayı benmari usulü eritin.
2. Krema ve kakaoyu çırpıp eritilmiş çikolatayla karıştırın.
3. Yumurta sarılarını şekerle çırpıp çikolatalı karışıma ekleyin.
4. Kadeh ya da kaselere paylaştırıp en az 2 saat buzdolabında dinlendirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_045';
update public.posts set recipe_text = '1. Bisküvileri ufalayıp eritilmiş tereyağıyla karıştırın, kalıba bastırıp tabanı oluşturun.
2. Krem peyniri, şekeri ve kremayı pürüzsüz olana kadar çırpın.
3. Karışımı bisküvi tabanının üzerine dökün, en az 4 saat buzdolabında dinlendirin.
4. Servis öncesi üzerini dilimlenmiş taze çilekle süsleyin.', recipe_is_ai_generated = false where recipe_id = 'recipe_046';
update public.posts set recipe_text = '1. Kuzu eti ince dilimleyip yüksek ateşte kavurun.
2. Salçayı su ile açıp kaynatarak domates sosunu hazırlayın.
3. Ekmeği küp doğrayıp servis tabağına yayın, üzerine et ve sosu ekleyin.
4. Bir yanına yoğurt koyup üzerine eritilmiş tereyağını cızırdatarak gezdirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_047';
update public.posts set recipe_text = '1. Kıymayı rendelenmiş soğan, pul biber ve tuzla iyice yoğurun, dinlendirin.
2. Harcı şişlere yassı ve uzun şekilde sarın.
3. Közde veya ızgarada çevirerek pişirin, yanında domates ve biberi de közleyin.
4. Sıcak ekmek ve maydanozla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_048';
update public.posts set recipe_text = '1. Kuzu kuşbaşıyı soğanla birlikte kısık ateşte 1 saat güveç şeklinde pişirin.
2. Patlıcanları ateşte veya fırında köz haline getirip kabuklarını soyun.
3. Tereyağında unu kavurup sütü azar azar ekleyerek beşamel kıvamına getirin, közlenmiş patlıcanı ve kaşarı ekleyip pürüzsüzleştirin.
4. Beğendiyi tabağa alıp üzerine sıcak kuzu güvecini koyarak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_049';
update public.posts set recipe_text = '1. Patlıcanların kabuklarını yer yer soyup az yağda hafifçe kızartın.
2. Soğan, biber ve sarımsağı zeytinyağında kavurup doğranmış domatesi ekleyin.
3. Patlıcanları ortadan yararak harcı içlerine doldurun.
4. Tepsiye dizip biraz su ilave ederek fırında veya ocakta yumuşayana kadar pişirin, soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_050';
update public.posts set recipe_text = '1. İnce bulguru sıcak suda 15 dakika bekletip kabartın.
2. Salçaları ve zeytinyağını ekleyip iyice karıştırın.
3. Küçük doğranmış domates, salatalık ve maydanozu ekleyin.
4. Limon suyunu gezdirip karıştırdıktan sonra soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_051';
update public.posts set recipe_text = '1. Haşlanmış kuru fasulyeyi süzüp bir kaba alın.
2. İnce doğranmış soğan, domates ve maydanozu ekleyin.
3. Zeytinyağı ve limon suyuyla harmanlayın.
4. Haşlanmış yumurta dilimleriyle süsleyerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_052';
update public.posts set recipe_text = '1. Un, yumurta ve suyla sert bir hamur yoğurup dinlendirin.
2. Kıyma ve rendelenmiş soğanı karıştırıp iç harcı hazırlayın.
3. Hamuru ince açıp küçük kareler halinde kesin, ortasına harçtan koyup kapatın.
4. Kaynar suda haşlayıp sarımsaklı yoğurt ve pul biberli tereyağıyla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_053';
update public.posts set recipe_text = '1. Beyaz peyniri ezip doğranmış maydanozla karıştırın.
2. Yufkaları üçgen şeritler halinde kesip bir ucuna harçtan koyun, sigara böreği şeklinde sarın.
3. Uçlarını çırpılmış yumurtayla yapıştırın.
4. Kızgın yağda her iki tarafı altın rengi olana kadar kızartıp sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_054';
update public.posts set recipe_text = '1. Un, maya, şeker ve ılık suyla yumuşak bir hamur yoğurup mayalanmaya bırakın.
2. Hamuru parçalayıp ince uzun şeritler haline getirin, ikişer ikişer bükerek halka şekli verin.
3. Pekmez şerbetine batırıp fırın tepsisine dizin.
4. Önceden ısıtılmış fırında altın rengi ve çıtır olana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_055';
update public.posts set recipe_text = '1. Şeker, su ve limon suyunu kaynatıp koyulaştırarak şerbeti hazırlayın, soğumaya bırakın.
2. Yufkayı ince ince didikleyip eritilmiş tereyağıyla harmanlayın.
3. Tepsiye yarısını serip üzerine peyniri, kalan yufkayı da üstüne kapatın.
4. Her iki tarafı altın rengi olana kadar pişirip sıcakken soğuk şerbeti gezdirin, dövülmüş cevizle servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_056';
update public.posts set recipe_text = '1. Nohut, kuru fasulye ve pirinci ayrı ayrı haşlayıp yumuşatın.
2. Hepsini geniş bir tencerede birleştirip üzerine su ekleyin.
3. Küp doğranmış elma ve şekeri ekleyip karıştırarak 30-40 dakika kaynatın.
4. Kaselere paylaştırıp üzerine ceviz ve tarçın serperek soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_057';
update public.posts set recipe_text = '1. Sütü şeker ve irmikle karıştırıp kısık ateşte koyulaşana kadar pişirin.
2. Karışımı yağlanmış bir tepsiye dökün.
3. Tepsiyi doğrudan ocak üzerinde altı hafifçe karamelize olana kadar pişirin.
4. Soğuyunca dilimleyip rulo şeklinde sararak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_058';
update public.posts set recipe_text = '1. Un, yumurta ve suyla yufka hamuru hazırlayıp ince yapraklar halinde açın.
2. Yufkaları kaynar tuzlu suda kısaca haşlayıp soğuk suya alın.
3. Tepsiye yufkaları eritilmiş tereyağı sürerek dizin, arasına peynir-maydanoz harcını serpin.
4. Üzerine süt gezdirip fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_059';
update public.posts set recipe_text = '1. Un, maya, ılık süt ve eritilmiş tereyağıyla yumuşak bir hamur yoğurup mayalandırın.
2. Hamurdan parçalar koparıp içine peynir koyarak yuvarlayın.
3. Üzerlerine çırpılmış yumurta sürün.
4. Önceden ısıtılmış fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_060';
update public.posts set recipe_text = '1. Ilık süt, maya ve şekeri karıştırıp 10 dakika bekletin.
2. Un ve eritilmiş tereyağını ekleyip yumuşak bir hamur yoğurun, mayalandırın.
3. Hamuru parçalayıp yuvarlayarak fırın tepsisine dizin, tekrar mayalandırın.
4. Üzerine çırpılmış yumurta sürüp fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_061';
update public.posts set recipe_text = '1. Zeytinyağında soğanı pembeleşene kadar kavurun.
2. Doğranmış havuç, patates ve salçayı ekleyip birkaç dakika soteleyin.
3. Haşlanmış fasulyeyi ve su ekleyip kısık ateşte sebzeler yumuşayana kadar pişirin.
4. Soğuduktan sonra limon dilimleriyle servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_062';
update public.posts set recipe_text = '1. Eti yüksek ateşte suyunu salıp çekene kadar kavurun.
2. Soğan ve sarımsağı ekleyip pembeleşene kadar kavurmaya devam edin.
3. Salça ve doğranmış domatesi ekleyip su ilave edin, kısık ateşte 40 dakika pişirin.
4. Küp doğranmış patatesi ekleyip et ve patatesler yumuşayana kadar pişirmeye devam edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_063';
update public.posts set recipe_text = '1. Etleri ayrı ayrı marine edip şişlere dizin.
2. Izgarayı iyice kızdırın.
3. Etleri ve sebzeleri çevirerek her tarafı eşit pişene kadar közleyin.
4. Sıcak ekmekle birlikte tek tabakta servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_064';
update public.posts set recipe_text = '1. Balık filetolarını zeytinyağı ve limon suyuyla marine edin.
2. Biber ve kabağı dilimleyip zeytinyağıyla harmanlayın.
3. Izgarada balığı ve sebzeleri çevirerek pişirin.
4. Limon dilimleriyle sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_065';
update public.posts set recipe_text = '1. Patlıcan ve patatesi dilimleyip hafifçe kızartın.
2. Soğanı kıymayla kavurup salça ve baharatları ekleyin.
3. Fırın kabına patlıcan, patates ve kıyma harcını sırayla dizin.
4. Üzerine dilimlenmiş domatesleri koyup fırında 30-35 dakika pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_066';
update public.posts set recipe_text = '1. Kabakları rendeleyip tuzlayın, suyunu sıkıp süzün.
2. Yumurta, un, peynir ve dereotunu ekleyip karıştırın.
3. Kızgın yağa kaşık yardımıyla harçtan alıp yayarak kızartın.
4. Her iki tarafı altın rengi olunca kağıt havluya alıp sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_067';
update public.posts set recipe_text = '1. Ispanağı doğrayıp soğanla birlikte hafifçe soteleyin, suyunu süzün.
2. Ispanağı peynir ve bir yumurtayla karıştırıp harcı hazırlayın.
3. Tepsiye eritilmiş tereyağı sürerek yufkaları dizin, arasına harcı serpin.
4. Üzerine çırpılmış yumurta sürüp fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_068';
update public.posts set recipe_text = '1. Eti tereyağında rengi dönene kadar kavurun.
2. Doğranmış soğanı ekleyip pembeleşene kadar pişirin, salçayı ilave edin.
3. Haşlanmış nohut ve su ekleyip kısık ateşte et yumuşayana kadar pişirin.
4. Sıcak, pilav eşliğinde servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_069';
update public.posts set recipe_text = '1. Yoğurdu bir kaba alıp soğuk suyla karıştırın.
2. Tuzu ekleyip köpürene kadar çırpın.
3. Buzla dolu bardaklara paylaştırıp servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_070';
update public.posts set recipe_text = '1. Un, maya ve suyla yumuşak bir hamur yoğurup dinlendirin.
2. Kıyma, rendelenmiş domates, biber, soğan ve maydanozu robotta çekip harcı hazırlayın.
3. Hamuru ince yuvarlaklar halinde açıp üzerine harcı ince tabaka halinde yayın.
4. Önceden ısıtılmış fırında kenarları çıtırlaşana kadar pişirip limonla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_071';
update public.posts set recipe_text = '1. Un, maya, su ve tuzla hamur yoğurup mayalandırın.
2. Hamuru kayık şeklinde açıp kenarlarını kıvırın.
3. Kıyma, doğranmış biber ve kaşarı karıştırıp hamurun üzerine yayın.
4. İsteğe bağlı ortasına yumurta kırıp önceden ısıtılmış fırında pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_072';
update public.posts set recipe_text = '1. Yoğurdu ezilmiş sarımsakla karıştırıp servis tabaklarına paylaştırın.
2. Kaynar suya biraz sirke ekleyip yumurtaları teker teker kırarak poşe yapın.
3. Poşe yumurtaları süzüp yoğurdun üzerine yerleştirin.
4. Tereyağını pul biberle kızdırıp yumurtaların üzerine gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_073';
update public.posts set recipe_text = '1. Un ve suyla yumuşak bir hamur yoğurup ince yufka halinde açın.
2. Yufkanın üzerine eritilmiş tereyağı sürüp kaymak ve dövülmüş cevizi serpin.
3. Yufkayı katlayarak dörde bölün.
4. Sacda veya tavada her iki tarafını altın rengi olana kadar pişirip şeker serperek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_074';
update public.posts set recipe_text = '1. Şeker ve suyu kaynatıp şerbeti hazırlayın, soğumaya bırakın.
2. Yumuşatılmış tereyağı, yumurta, un ve irmiği yoğurup hamur hazırlayın.
3. Hamurdan küçük yuvarlaklar yapıp fırın tepsisine dizin.
4. Altın rengi olana kadar pişirip sıcak kurabiyelerin üzerine soğuk şerbeti gezdirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_075';
update public.posts set recipe_text = '1. Yumuşak tereyağı, şeker ve vanilyayı çırpın.
2. Unu ekleyip yumuşak bir hamur elde edene kadar yoğurun.
3. Küçük parçalar koparıp hilal veya top şeklinde şekillendirin.
4. Önceden ısıtılmış fırında pişirip soğuduktan sonra pudra şekerine bulayın.', recipe_is_ai_generated = false where recipe_id = 'recipe_076';
update public.posts set recipe_text = '1. Şeker, su ve limon suyunu kaynatıp şerbeti hazırlayın, soğutun.
2. Tel kadayıfı eritilmiş tereyağıyla harmanlayın.
3. Kadayıfın yarısını tepsiye serip üzerine dövülmüş cevizi yayın, kalanını üstüne kapatın.
4. Fırında altın rengi olana kadar pişirip sıcakken soğuk şerbeti gezdirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_077';
update public.posts set recipe_text = '1. Elmaların çekirdek kısımlarını oyarak çıkarın.
2. Dövülmüş ceviz, bal ve tarçını karıştırıp elmaların içine doldurun.
3. Üzerine küçük birer parça tereyağı koyup fırın kabına dizin.
4. Fırında elmalar yumuşayana kadar 25-30 dakika pişirip sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_078';
update public.posts set recipe_text = '1. Tavuk göğsünü haşlayıp didikleyin, suyunu ayırın.
2. Tereyağında soğanı kavurup pirinci ekleyerek birkaç dakika kavurun.
3. Ilık tavuk suyunu ekleyip kısık ateşte pirinç suyunu çekene kadar pişirin.
4. Didiklenmiş tavuğu karıştırıp demlendirdikten sonra servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_079';
update public.posts set recipe_text = '1. Biberlerin kapaklarını kesip içlerini temizleyin.
2. Kıyma, pirinç, rendelenmiş soğan ve yarım salçayı karıştırıp iç harcı hazırlayın.
3. Biberleri harçla doldurup tencereye dizin.
4. Kalan salçayı su ile açıp üzerine dökün, kısık ateşte 40-45 dakika pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_080';
update public.posts set recipe_text = '1. Patatesleri haşlayıp soğuduktan sonra küp doğrayın.
2. Yumurtaları haşlayıp küçük parçalar halinde doğrayın.
3. İnce doğranmış soğan ve dereotunu ekleyin.
4. Mayonezle harmanlayıp soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_081';
update public.posts set recipe_text = '1. Tereyağında çam fıstığını hafifçe kavurup kenara alın.
2. Aynı tereyağında irmiği pembeleşene ve mis gibi koku yayılana kadar kavurun.
3. Süt ve şekeri ayrı bir tencerede kaynatıp sıcak haliyle irmiğin üzerine dökün, karıştırmadan kısık ateşte demlendirin.
4. Karıştırıp servis tabağına alın, üzerine çam fıstığı serperek sıcak veya ılık servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_082';
update public.posts set recipe_text = '1. Kıyma, ezilmiş sarımsak ve yumurtayı yoğurup küçük köfteler yapın.
2. Köfteleri hafifçe kızartıp fırın kabına dizin.
3. Küp doğranmış patatesleri köftelerin arasına yerleştirin.
4. Üzerine dilimlenmiş domatesleri koyup fırında 30-35 dakika pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_083';
update public.posts set recipe_text = '1. Tereyağında soğan ve biberi yumuşayana kadar kavurun.
2. Rendelenmiş domatesi ekleyip birkaç dakika pişirin.
3. Bulguru ekleyip kısaca kavurun, sıcak su ilave edin.
4. Kısık ateşte suyunu çekene kadar pişirip demlendirdikten sonra servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_084';
update public.posts set recipe_text = '1. Tüm sebzeleri iri küpler halinde doğrayın.
2. Zeytinyağında sırasıyla patates, patlıcan ve kabağı hafifçe soteleyin.
3. Biber ve rendelenmiş domatesi ekleyip karıştırın.
4. Az su ilave edip kısık ateşte sebzeler yumuşayana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_085';
update public.posts set recipe_text = '1. Tereyağında soğanı pembeleşene kadar kavurup unu ekleyerek kısaca kavurun.
2. Rendelenmiş domatesleri ekleyip birkaç dakika pişirin.
3. Sıcak su ilave edip 15 dakika kaynatın, blenderdan geçirin.
4. Sütü ekleyip karıştırarak bir taşım kaynatıp servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_086';
update public.posts set recipe_text = '1. Kıyma ve soğanı bir tencerede kavurun.
2. Doğranmış ıspanağı ekleyip suyunu salana kadar pişirin.
3. Pirinç ve az su ekleyip kısık ateşte pirinç yumuşayana kadar pişirin.
4. Yanında yoğurtla servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_087';
update public.posts set recipe_text = '1. Tavuk göğsünü küp doğrayıp yoğurt ve ezilmiş sarımsakla marine edin, en az 1 saat bekletin.
2. Tavukları biber ve domatesle sırayla şişlere dizin.
3. Izgarada çevirerek her tarafı pişene kadar közleyin.
4. Sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_088';
update public.posts set recipe_text = '1. Makarnayı tarifine göre haşlayıp süzün.
2. Tereyağında unu kavurup sütü azar azar ekleyerek beşamel sos hazırlayın.
3. Sosun yarısını rendelenmiş kaşarla karıştırıp makarnayla harmanlayın.
4. Fırın kabına alıp üzerine kalan kaşarı serpin, fırında peynir eriyip kızarana kadar pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_089';
update public.posts set recipe_text = '1. Domates, soğan ve biberi küçük küpler halinde doğrayın.
2. Salça, limon suyu ve zeytinyağını ekleyip karıştırın.
3. Doğranmış maydanozu ilave edin.
4. En az 15 dakika dinlendirip soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_090';
update public.posts set recipe_text = '1. Un, maya, su ve tuzla hamur yoğurup mayalandırın.
2. Hamuru kayık şeklinde açıp kenarlarını kıvırın.
3. Dilimlenmiş sucuk ve rendelenmiş kaşarı üzerine yayın.
4. Ortasına yumurta kırıp önceden ısıtılmış fırında pişirin.', recipe_is_ai_generated = false where recipe_id = 'recipe_091';
update public.posts set recipe_text = '1. Havuçları rendeleyip zeytinyağında yumuşayana kadar soteleyin.
2. Soğuduktan sonra ezilmiş sarımsaklı yoğurtla karıştırın.
3. Doğranmış dereotunu ekleyin.
4. Soğuk meze olarak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_092';
update public.posts set recipe_text = '1. Tereyağında soğanı kavurup doğranmış kabak ve patatesi ekleyin.
2. Üzerini geçecek kadar sıcak su ekleyip sebzeler yumuşayana kadar pişirin.
3. Blenderdan geçirip sütü ekleyin.
4. Bir taşım kaynatıp zeytinyağı gezdirerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_093';
update public.posts set recipe_text = '1. Havuçları rendeleyip hafifçe haşlayın ve suyunu süzün.
2. Yumurta, un, dövülmüş ceviz ve maydanozu ekleyip karıştırın.
3. Küçük köfteler halinde şekillendirin.
4. Tavada az yağda her iki tarafını kızartıp sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_094';
update public.posts set recipe_text = '1. Ekmek içini ıslatıp sıkarak kıymaya ekleyin.
2. Rendelenmiş soğan, maydanoz ve pul biberle iyice yoğurup dinlendirin.
3. Harçtan parçalar alıp şişlere uzun şekilde sarın.
4. Izgarada çevirerek pişirip sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_095';
update public.posts set recipe_text = '1. Pirinci az suyla yumuşayana kadar haşlayın.
2. Süt ve şekeri ekleyip karıştırarak koyulaşana kadar pişirin.
3. Çırpılmış yumurta ve vanilyayı ekleyip karıştırın, kaselere paylaştırın.
4. Fırında üzeri hafif kızarana kadar pişirip soğuduktan sonra servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_096';
update public.posts set recipe_text = '1. Pirinci bol suda yumuşayana kadar haşlayın.
2. Şeker ve pekmezi ekleyip koyulaşana kadar kısık ateşte pişirin.
3. Kaselere paylaştırıp soğumaya bırakın.
4. Üzerine çam fıstığı serperek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_097';
update public.posts set recipe_text = '1. Kabakları dilimleyip haşlayın veya buharda pişirin.
2. Soğuduktan sonra hafifçe ezin.
3. Ezilmiş sarımsaklı yoğurt ve doğranmış dereotuyla karıştırın.
4. Üzerine zeytinyağı gezdirerek soğuk servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_098';
update public.posts set recipe_text = '1. Zeytinyağında soğan ve havucu yumuşayana kadar kavurun.
2. Salçayı ekleyip kısaca kavurun.
3. Haşlanmış nohut ve suyunu ekleyip kısık ateşte 20 dakika pişirin.
4. Sıcak veya ılık servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_099';
update public.posts set recipe_text = '1. Eti oda sıcaklığına getirip her iki tarafına tuz ve karabiber gezdirin.
2. Kızgın tavada yüksek ateşte her iki tarafını mühürleyin.
3. Tereyağı ve ezilmiş sarımsağı ekleyip eti kaşıkla kendi yağıyla ıslatarak pişirin.
4. Birkaç dakika dinlendirip dilimleyerek servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_100';
update public.posts set recipe_text = '1. Eti kuru bir tavada suyunu salıp çekene kadar kavurun.
2. Tereyağını ekleyip eti kendi yağında kızarana kadar pişirmeye devam edin.
3. Doğranmış soğanı ekleyip yumuşayana kadar kavurun.
4. Karabiberle tatlandırıp sıcak servis edin.', recipe_is_ai_generated = false where recipe_id = 'recipe_101';
