-- Backfills recipe_text for the 125 user-submitted posts (fake seeded
-- community profiles, pre-launch feed population). recipe_text content
-- was drafted by an LLM (Claude, in-chat) grounded in each post's
-- matched recipes.json dish + its own ingredient_ids, paraphrased so it
-- doesn't repeat the official post's recipe_text verbatim for the same
-- dish. recipe_is_ai_generated is deliberately a realistic MIX, not all
-- one value: ~60% simulate a user who left the field blank and got the
-- app's real AI-generate feature (neutral tone), ~40% simulate a user
-- who typed their own recipe (casual, first-person tone) and are left
-- unmarked, matching how the feature actually behaves going forward.
-- Generated by scratchpad render_sql.py, run once.

update public.posts set recipe_text = '1. Soğanı tereyağında hafif pembeleşene kadar kavurup unu ilave edin.
2. Rendelenmiş domatesleri ekleyip birkaç dakika daha pişirin.
3. Sıcak suyu ilave edip 15 dakika kadar kaynattıktan sonra blenderdan geçirin.
4. Sütü katıp bir taşım kaynatın, sıcak servis edin.', recipe_is_ai_generated = true where id = '50835035-314e-42f5-82e3-ed84dfdf46aa';
update public.posts set recipe_text = '1. Yumurtaları bir tutam tuzla iyice çırpın.
2. Tereyağını tavada eritip yumurtaları dökün.
3. Yarısına rendelenmiş kaşar serpip katlayın.
4. Peynir eriyene kadar pişirip sıcakken servis edin.', recipe_is_ai_generated = true where id = '746b9ef6-1d9b-4cde-99fb-f26e84b1414e';
update public.posts set recipe_text = '1. Un, yumurta ve suyla sert kıvamda hamur yoğurup dinlendirin.
2. Kıyma ile rendelenmiş soğanı karıştırıp iç harcını hazırlayın.
3. Hamuru ince açıp küçük kareler kesin, ortasına harçtan koyup kapatın.
4. Kaynar suda haşlayıp sarımsaklı yoğurt ve pul biberli tereyağıyla servis edin.', recipe_is_ai_generated = true where id = 'a731279f-a6af-4906-a257-a16e41e9a7ff';
update public.posts set recipe_text = '1. Domates, salatalık, biber ve soğanı küçük küpler halinde doğrayın.
2. İnce kıyılmış maydanozu ekleyip hepsini bir kapta birleştirin.
3. Zeytinyağı, limon suyu ve tuzla harmanlayın.
4. İyice karıştırıp hemen servis edin.', recipe_is_ai_generated = true where id = '4886d446-d431-465c-b9f3-35518dee085c';
update public.posts set recipe_text = '1. Yumurtaları bir tutam tuzla çırpın.
2. Tereyağını sıcak tavada eritin.
3. Yumurtayı dökün, kenarları pişince rendelenmiş kaşarı üzerine serpin.
4. Yarısını katlayıp kaşar eriyene kadar pişirmeye devam edin.', recipe_is_ai_generated = true where id = '56720360-a1b9-4251-854e-8f46778ffe9d';
update public.posts set recipe_text = '1. Zeytinyağında soğan ve havucu yumuşayana kadar soteleyin.
2. Salçayı ekleyip birkaç dakika kavurun.
3. Haşlanmış nohudu suyuyla birlikte ekleyip kısık ateşte 20 dakika pişirin.
4. Ilık ya da soğuk servis edin.', recipe_is_ai_generated = true where id = '04712a4b-9e0a-4109-82a0-14d2c06ec732';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Fırını 200 dereceye ısıtıp filetoları fırın kağıtlı tepsiye dizin.
2. Ezilmiş sarımsak, zeytinyağı ve limon suyunu karıştırıp üzerine gezdirin.
3. Balık kolayca dağılana kadar 15-18 dakika fırınlayın.
4. Maydanoz ve limon dilimiyle servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '62eaf5f1-5299-4618-a6ab-690f72b1a761';
update public.posts set recipe_text = '1. Havuçları rendeleyip zeytinyağında yumuşayana kadar soteleyin.
2. Soğuduktan sonra ezilmiş sarımsaklı yoğurtla karıştırın.
3. Üzerine doğranmış dereotu ekleyin.
4. Soğuk meze olarak servis edin.', recipe_is_ai_generated = true where id = '75d82852-d10b-4fe6-97c0-14dd9db2bd7f';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Patlıcanları kızartıp uzunlamasına yarın.
2. Kıymayı soğan, biber ve sarımsakla kavurun.
3. Domates ve salça ekleyip koyu bir iç harç elde edin.
4. Patlıcanları doldurup üzerine domates dilimiyle fırınlayın.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '5b6adf95-aad7-4a2e-9df0-ca4813f6c81b';
update public.posts set recipe_text = 'Şöyle hallettim:
1. İnce bulguru sıcak suda 15 dakika bekletip kabartın.
2. İki salçayı ve zeytinyağını ekleyip iyice yoğurun.
3. Küçük doğranmış domates, salatalık ve maydanozu karıştırın.
4. Limon suyunu gezdirip soğuk servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '3ac67aa9-18ce-46da-bcf5-4b97dbb5e6a6';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Eti tereyağında rengi dönene kadar kavurun.
2. Soğanı ekleyip pembeleşince salçayı ilave edin.
3. Haşlanmış nohut ve suyunu ekleyip et yumuşayana kadar pişirin.
4. Pilav eşliğinde sıcak servis edin.', recipe_is_ai_generated = false where id = 'f8f77935-69db-4761-9172-0a0658adf619';
update public.posts set recipe_text = '1. Tavuk göğsünü haşlayıp didikleyin, suyunu ayırın.
2. Tereyağında soğanı kavurup pirinci birkaç dakika kavurun.
3. Ilık tavuk suyunu ekleyip pirinç suyunu çekene kadar pişirin.
4. Didiklenmiş tavuğu karıştırıp demlendirdikten sonra servis edin.', recipe_is_ai_generated = true where id = '210ef47d-ba5d-42c9-85e6-18c79e27c0aa';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Tavuk göğsünü küp doğrayıp yoğurt ve sarımsakla en az 1 saat marine edin.
2. Tavukları biber ve domatesle şişlere dizin.
3. Izgarada çevirerek her tarafı pişene kadar közleyin.
4. Sıcak servis edin.', recipe_is_ai_generated = false where id = '241ea6f5-2200-4f18-b354-3a9d4c4bf549';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Un ve suyla yumuşak hamur yoğurup ince açın.
2. Üzerine eritilmiş tereyağı sürüp kaymak ve dövülmüş ceviz serpin.
3. Yufkayı katlayarak dörde bölün.
4. Sacda iki tarafını altın rengi olana kadar pişirip şeker serperek servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '58cf3a6b-84f7-4433-bf58-52cabbcef13a';
update public.posts set recipe_text = '1. Biberlerin kapağını kesip içini temizleyin.
2. Kıyma, pirinç, soğan ve yarım salçayı yoğurup iç harcı hazırlayın.
3. Biberleri doldurup tencereye dizin.
4. Kalan salçalı suyu üzerine dökün, kısık ateşte 40-45 dakika pişirin.', recipe_is_ai_generated = true where id = 'ecdab528-ff0f-458b-a3ad-dc5a5c65c924';
update public.posts set recipe_text = '1. Soğanı ince doğrayıp zeytinyağında kavurun.
2. Havucu rendeleyip ekleyip birlikte soteleyin.
3. Salçayı katıp kokusu çıkana kadar kavurun.
4. Nohudu ve suyunu ilave edip kısık ateşte pişirin.
5. Oda sıcaklığında servis edilmesi daha lezzetli oluyor.', recipe_is_ai_generated = true where id = '61e0df06-9227-482d-b008-fb8beaefbce1';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Şeker, su ve limon suyunu kaynatıp şerbeti hazırlayıp soğutun.
2. Yufkayı didikleyip eritilmiş tereyağıyla harmanlayın.
3. Tepsiye yarısını serip peyniri koyup kalan yufkayla kapatın.
4. İki tarafı altın rengi olana kadar pişirip soğuk şerbeti gezdirin, cevizle servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = 'd56ce1ce-aa44-4d48-a802-8072577ca554';
update public.posts set recipe_text = '1. Pirinci az suyla yumuşayana kadar haşlayın.
2. Süt ve şekeri ekleyip koyulaşana kadar pişirin.
3. Çırpılmış yumurta ve vanilyayı katıp kaselere paylaştırın.
4. Fırında üzeri hafif kızarana kadar pişirip soğutarak servis edin.', recipe_is_ai_generated = true where id = '91191959-faec-452b-986a-00262509b2af';
update public.posts set recipe_text = '1. Havuçları rendeleyip hafifçe haşlayın.
2. Yoğurt ve ezilmiş sarımsağı çırpın.
3. Haşlanmış havuçları yoğurtla karıştırın.
4. Üzerine zeytinyağı gezdirip dereotuyla süsleyin.', recipe_is_ai_generated = true where id = '7e931f8c-f939-4ddc-88b2-dbd8fde537dc';
update public.posts set recipe_text = '1. Cezveye soğuk su, kahve ve istediğiniz kadar şeker ekleyip karıştırın.
2. Kısık ateşte, karıştırmadan yavaşça ısıtın.
3. Köpük kabarınca ocaktan alıp köpüğü fincana paylaştırın.
4. Cezveyi tekrar ocağa koyup son bir kaynatmayla fincana boşaltın.', recipe_is_ai_generated = true where id = '4413512c-1169-47b4-9284-48132a96c0c6';
update public.posts set recipe_text = '1. Bamyaların saplarını temizleyip limonlu suyla ovarak yıkayın.
2. Zeytinyağında soğanı pembeleşene kadar kavurun.
3. Rendelenmiş domates ve bamyaları ekleyip 25-30 dakika kısık ateşte pişirin.
4. Ilık ya da soğuk servis edin.', recipe_is_ai_generated = true where id = 'ad6f20e1-1030-49be-90c0-9f0eef3c69f6';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Doğranmış yeşil biberi yağda yumuşayana kadar soteleyin.
2. Küp domatesi ekleyip sulu bir kıvama gelene kadar pişirin.
3. Yumurtaları kırıp hafifçe karıştırarak istediğiniz kıvama getirin.
4. Pul biber serpip tavadan sıcak servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = '61421aba-f9b2-4b1e-a047-1a844247500e';
update public.posts set recipe_text = 'Bende şöyle oldu:
1. Lahana yapraklarını kaynar suda yumuşayana kadar haşlayın.
2. Kıyma, pirinç, soğan ve salçayı yoğurup iç harcı hazırlayın.
3. Yaprakları harçla doldurup sıkıca sarın, tencereye dizin.
4. Sıcak su ilave edip kısık ateşte 45-50 dakika pişirin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = 'b6268adc-b253-46a1-89fc-3f8450ef475e';
update public.posts set recipe_text = '1. Yoğurdu bir kaba alıp soğuk suyla karıştırın.
2. Tuzu ekleyip köpürene kadar çırpın.
3. Buzlu bardaklara paylaştırıp hemen servis edin.', recipe_is_ai_generated = true where id = 'f858db08-266b-456c-9d7d-f48228072eaa';
update public.posts set recipe_text = '1. Kıyma, sarımsak ve yumurtayı yoğurup küçük köfteler şekillendirin.
2. Köfteleri hafifçe kızartıp fırın kabına dizin.
3. Küp patatesleri köftelerin arasına yerleştirin.
4. Üzerine domates dilimleriyle 30-35 dakika fırınlayın.', recipe_is_ai_generated = true where id = '195a032d-cfc1-427f-a032-c03a2c60466c';
update public.posts set recipe_text = '1. Kabakları rendeleyip tuzlayın, suyunu sıkıp süzün.
2. Yumurta, un, peynir ve dereotunu ekleyip karıştırın.
3. Kızgın yağda kaşıkla alıp yayarak kızartın.
4. Altın rengi olunca kağıt havluya alıp sıcak servis edin.', recipe_is_ai_generated = true where id = 'd1e7dd97-1c00-4a97-b53a-c101585030eb';
update public.posts set recipe_text = '1. Patlıcanları kızartıp uzunlamasına yarın.
2. Kıymayı soğan, biber ve sarımsakla kavurun.
3. Domates ve salça ekleyip koyu bir iç harç elde edin.
4. Patlıcanları doldurup üzerine domates dilimiyle fırınlayın.', recipe_is_ai_generated = true where id = '863ded44-4148-4c52-bab3-8796c629e637';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Tarhanayı ılık suyla açıp pürüzsüz olana kadar karıştırın.
2. Tereyağında salçayı birkaç dakika kavurun.
3. Açılmış tarhanayı ekleyip 15-20 dakika arada karıştırarak pişirin.
4. Pul biber ve naneli tereyağı gezdirerek sıcak servis edin.', recipe_is_ai_generated = false where id = '48ea8ba3-2c92-4e08-8c5f-8fdd0accd63a';
update public.posts set recipe_text = '1. Tereyağlı yufka katmanlarının arasına kıyılmış ceviz serperek dizin.
2. Fırınlamadan önce dilim şeklinde kesin.
3. Altın rengi ve çıtır olana kadar fırınlayın.
4. Sıcak baklavaya soğuk limonlu şerbeti gezdirip çekmesini bekleyin.', recipe_is_ai_generated = true where id = '5f21a0e6-b60c-45ef-bf0d-920a1de430f0';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Tüm sebzeleri iri küpler halinde doğrayın.
2. Zeytinyağında sırasıyla patates, patlıcan ve kabağı hafifçe soteleyin.
3. Biber ve rendelenmiş domatesi ekleyin.
4. Az su ilave edip sebzeler yumuşayana kadar kısık ateşte pişirin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = 'ea3e5198-e5b2-424d-b681-869259d92980';
update public.posts set recipe_text = '1. Un, maya ve suyla yumuşak hamur yoğurup dinlendirin.
2. Kıyma, domates, biber, soğan ve maydanozu çekip harcı hazırlayın.
3. Hamuru ince açıp harcı ince tabaka halinde yayın.
4. Isıtılmış fırında kenarları çıtırlaşana kadar pişirip limonla servis edin.', recipe_is_ai_generated = false where id = 'ac2d60b5-dcf4-4df0-9c32-e34029820b91';
update public.posts set recipe_text = '1. Patlıcanları ateşte veya fırında yumuşayana kadar közleyin.
2. İçini çıkarıp kısa süre süzülmeye bırakın.
3. Tahin, limon suyu ve sarımsakla ezin.
4. Servisten önce zeytinyağı gezdirin.', recipe_is_ai_generated = true where id = '04bb50ab-0cc2-44f0-b735-0da255c17e6f';
update public.posts set recipe_text = '1. Yoğurdu sarımsakla karıştırıp servis tabaklarına paylaştırın.
2. Kaynar suya biraz sirke katıp yumurtaları teker teker kırarak poşe yapın.
3. Poşe yumurtaları süzüp yoğurdun üzerine yerleştirin.
4. Pul biberli tereyağını cızırdatarak üzerine gezdirin.', recipe_is_ai_generated = true where id = 'c904642c-d4fb-4517-bc61-d463f0f76f2c';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Kıymayı soğan, pul biber ve tuzla iyice yoğurup dinlendirin.
2. Harcı şişlere yassı ve uzun şekilde sarın.
3. Közde çevirerek pişirin, domates ve biberi de yanında közleyin.
4. Sıcak ekmek ve maydanozla servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = 'af636636-2bba-41df-8689-25f23a711ddb';
update public.posts set recipe_text = '1. Kabakları rendeleyip tuzlayın, 10 dakika sonra suyunu sıkın.
2. Yumurta, un ve beyaz peyniri ekleyip karıştırın.
3. Dereotunu doğrayıp harca katın.
4. Kaşıkla alıp sıcak yağda iki tarafını da kızartın.', recipe_is_ai_generated = true where id = '85307cd3-cca2-4b67-b692-c6e2ab989d81';
update public.posts set recipe_text = '1. Un, yumurta ve suyla hamuru yoğurup yarım saat dinlendirin.
2. Kıymayı rendelenmiş soğan ve baharatla karıştırıp iç harcı hazırlayın.
3. Hamuru ince açıp küçük kareler halinde kesin.
4. Her karenin ortasına harçtan koyup köşelerinden kapatın.
5. Kaynayan suda haşlayıp sarımsaklı yoğurt ve tereyağlı sosla servis edin.', recipe_is_ai_generated = true where id = '227f26c0-bcb0-4c86-8a02-a96400532500';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Pirinci bol suda yumuşayana kadar haşlayın.
2. Şeker ve pekmezi ekleyip koyulaşana kadar kısık ateşte pişirin.
3. Kaselere paylaştırıp soğumaya bırakın.
4. Üzerine çam fıstığı serperek servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = 'a48532d4-f511-425c-a710-ab61a5ec0406';
update public.posts set recipe_text = '1. Bal kabağını kalın dilimleyip kabuğunu soyun.
2. Üzerine şeker serpip 1-2 saat dinlendirin.
3. Kendi suyunda kısık ateşte şerbeti koyulaşana kadar pişirin.
4. Soğuduktan sonra ceviz ve tarçınla servis edin.', recipe_is_ai_generated = true where id = '517cd5cb-f343-4752-9a02-767f6082f5e1';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Soğanı tereyağında pembeleşene kadar kavurup salçayı ekleyin.
2. Mercimek, bulgur ve pirinci suyla birlikte katın.
3. Ara ara karıştırarak 30 dakika kadar pişirin.
4. Naneli pul biberli tereyağı gezdirerek servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = 'ac034070-4e00-4fcd-b504-b4eac07f329f';
update public.posts set recipe_text = '1. Patlıcanları yer yer soyup az yağda hafifçe kızartın.
2. Soğan, biber ve sarımsağı kavurup domatesi ekleyin.
3. Patlıcanları yarıp harcı içine doldurun.
4. Az suyla fırında ya da ocakta yumuşayana kadar pişirip soğuk servis edin.', recipe_is_ai_generated = true where id = 'a58271e5-3607-44ec-8314-ccf2670ab030';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Un, maya ve suyla yumuşak hamur yoğurup dinlendirin.
2. Kıyma, domates, biber, soğan ve maydanozu çekip harcı hazırlayın.
3. Hamuru ince açıp harcı ince tabaka halinde yayın.
4. Isıtılmış fırında kenarları çıtırlaşana kadar pişirip limonla servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '703a53b4-db4d-4048-8e82-0b19016644ff';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. İnce bulguru sıcak suda 15 dakika bekletip yumuşatın.
2. Salçalar, ceviz ve limon suyunu ekleyip uzun süre yoğurun.
3. Maydanozu karıştırıp küçük parçalar şekillendirin.
4. Marul yaprağına sarıp soğuk şalgamla servis edin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = 'a145f858-0cf9-42a9-8780-6eb694529cee';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Tavuk butlarını ve patatesleri zeytinyağı ve kırmızı toz biberle harmanlayın.
2. Fırın tepsisine tek sıra dizin.
3. Yüksek ısıda bir kez çevirerek altın rengi olana kadar pişirin.
4. Servisten önce kısa süre dinlendirin.', recipe_is_ai_generated = false where id = '753243e8-42c1-48c6-b834-cc5421e25269';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Pirinci yıkayıp kısa süre bekletin.
2. Soğanı kavurup süzülmüş nohudu ekleyin.
3. Pirinci ekleyip kavurduktan sonra sıcak su ilave edin.
4. Pirinç yumuşayana kadar pişirip demlendirerek servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = 'b322a88f-6962-4fca-81af-5e5f22dd0885';
update public.posts set recipe_text = '1. Etleri ayrı ayrı marine edip şişlere dizin.
2. Izgarayı iyice kızdırın.
3. Etleri ve sebzeleri çevirerek eşit pişene kadar közleyin.
4. Sıcak ekmekle tek tabakta servis edin.', recipe_is_ai_generated = true where id = '65d2cf69-20d4-4f5a-86cb-ccfb7f89b3d2';
update public.posts set recipe_text = '1. Salep tozunu birkaç kaşık soğuk sütle pürüzsüz olana kadar karıştırın.
2. Kalan sütü ve şekeri tencerede ısıtın.
3. Salep karışımını ekleyip sürekli karıştırarak koyulaştırın.
4. Üzerine tarçın serperek sıcak servis edin.', recipe_is_ai_generated = true where id = '2ec343c9-14bd-4b54-a052-ac421006317f';
update public.posts set recipe_text = '1. Doğranmış yeşil biberi yağda yumuşayana kadar soteleyin.
2. Küp domatesi ekleyip sulu bir kıvama gelene kadar pişirin.
3. Yumurtaları kırıp hafifçe karıştırarak istediğiniz kıvama getirin.
4. Pul biber serpip tavadan sıcak servis edin.', recipe_is_ai_generated = true where id = '4db43635-7239-4153-913a-b7993e68fc71';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Etleri ayrı ayrı marine edip şişlere dizin.
2. Izgarayı iyice kızdırın.
3. Etleri ve sebzeleri çevirerek eşit pişene kadar közleyin.
4. Sıcak ekmekle tek tabakta servis edin.', recipe_is_ai_generated = false where id = '8e2e9625-45ef-4a7f-bba9-9dbcbc25fd2b';
update public.posts set recipe_text = '1. Un, maya, ılık süt ve tereyağıyla hamur yoğurup mayalandırın.
2. Parçalar koparıp içine peynir koyarak yuvarlayın.
3. Üzerlerine çırpılmış yumurta sürün.
4. Isıtılmış fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = true where id = '00d2a807-18cf-48d3-8296-d301da134de4';
update public.posts set recipe_text = '1. Doğranmış domates ve yeşil biberi yağda kavurun.
2. Domatesler suyunu salana kadar pişirmeye devam edin.
3. Pul biber ekleyip yumurtaları kırın.
4. Yumurta kıvamına gelene kadar karıştırmadan pişirin.', recipe_is_ai_generated = true where id = 'dcd8abf4-a962-462d-a3e8-414f809473ee';
update public.posts set recipe_text = 'Bende şöyle oldu:
1. Un, yumurta ve suyla sert kıvamda hamur yoğurup dinlendirin.
2. Kıyma ile rendelenmiş soğanı karıştırıp iç harcını hazırlayın.
3. Hamuru ince açıp küçük kareler kesin, ortasına harçtan koyup kapatın.
4. Kaynar suda haşlayıp sarımsaklı yoğurt ve pul biberli tereyağıyla servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '0834d273-4b66-42fd-a002-9265874824ac';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Tereyağlı yufka katmanlarının arasına kıyılmış ceviz serperek dizin.
2. Fırınlamadan önce dilim şeklinde kesin.
3. Altın rengi ve çıtır olana kadar fırınlayın.
4. Sıcak baklavaya soğuk limonlu şerbeti gezdirip çekmesini bekleyin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = '2d4e86a7-ed52-4dae-9318-736cb5384042';
update public.posts set recipe_text = '1. Yumuşak tereyağı, şeker ve vanilyayı çırpın.
2. Unu ekleyip yumuşak bir hamur elde edene kadar yoğurun.
3. Küçük parçalar koparıp şekillendirin.
4. Fırında pişirip soğuduktan sonra pudra şekerine bulayın.', recipe_is_ai_generated = true where id = 'f03983cb-c103-42d1-987b-cabf8523e1b7';
update public.posts set recipe_text = '1. Patlıcanları yer yer soyup az yağda hafifçe kızartın.
2. Soğan, biber ve sarımsağı kavurup domatesi ekleyin.
3. Patlıcanları yarıp harcı içine doldurun.
4. Az suyla fırında ya da ocakta yumuşayana kadar pişirip soğuk servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = 'c0741225-f98e-40d9-9b38-80c483ad394b';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Tüm sebzeleri iri parçalar halinde doğrayın.
2. Zeytinyağı ve sarımsakla bir güveç kabına dizin.
3. Kapağını kapatıp ara sıra karıştırarak kısık ateşte pişirin.
4. Sıcak ya da oda sıcaklığında servis edin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = '42070e3f-ce1f-44d6-b41d-e2defbe52a45';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Patlıcanları ateşte veya fırında yumuşayana kadar közleyin.
2. İçini çıkarıp kısa süre süzülmeye bırakın.
3. Tahin, limon suyu ve sarımsakla ezin.
4. Servisten önce zeytinyağı gezdirin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = 'b766a8bf-8ef6-4938-a616-fcf72fc72bd1';
update public.posts set recipe_text = '1. Kuzu eti ince dilimleyip yüksek ateşte kavurun.
2. Salçayı su ile açıp kaynatarak domates sosunu hazırlayın.
3. Küp ekmeği tabağa yayıp üzerine et ve sosu ekleyin.
4. Yanına yoğurt koyup üzerine cızırtan tereyağı gezdirin.', recipe_is_ai_generated = true where id = '8375a6fb-1c75-4a95-b38c-868f024c4318';
update public.posts set recipe_text = '1. Tüm sebzeleri iri küpler halinde doğrayın.
2. Zeytinyağında sırasıyla patates, patlıcan ve kabağı hafifçe soteleyin.
3. Biber ve rendelenmiş domatesi ekleyin.
4. Az su ilave edip sebzeler yumuşayana kadar kısık ateşte pişirin.', recipe_is_ai_generated = true where id = 'ac8f95f0-da90-4b12-8d54-b3ff342f530c';
update public.posts set recipe_text = '1. Ispanağı soğanla hafifçe soteleyip suyunu süzün.
2. Peynir ve bir yumurtayla karıştırıp harcı hazırlayın.
3. Yufkaları tereyağlı tepsiye dizip arasına harcı serpin.
4. Üzerine yumurta sürüp fırında altın rengi olana kadar pişirin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = 'fc08ae9f-4fbd-4154-8304-22d65f4f9f93';
update public.posts set recipe_text = '1. Eti ince dilimleyip tereyağında hızlıca mühürleyin.
2. Ekmekleri küp küp doğrayıp bir tabağa dizin.
3. Domatesleri salçayla birlikte kaynatıp sos hazırlayın.
4. Eti ekmeklerin üzerine dizip sosu gezdirin.
5. Üzerine yoğurt ve eritilmiş tereyağı ekleyerek servis edin.', recipe_is_ai_generated = true where id = '4f44a715-d5da-4f94-8463-83099cfccaaa';
update public.posts set recipe_text = '1. Salep tozu ile birkaç kaşık soğuk sütü karıştırıp topaksız hale getirin.
2. Geri kalan sütü şekerle birlikte kaynamaya yakın ısıtın.
3. Salep karışımını ekleyip kısık ateşte koyulaşana kadar karıştırarak pişirin.
4. Sıcak servis edip üzerine bolca tarçın serpin.', recipe_is_ai_generated = true where id = 'c6f8bcf9-dfc5-4a07-8b76-bbc4995c38ec';
update public.posts set recipe_text = '1. Unu yumurta ve suyla yoğurup üzeri örtülü dinlendirin.
2. Kıyma ve rendelenmiş soğanla iç harcı hazırlayın.
3. Hamuru yufka gibi ince açıp küçük kareler kesin.
4. Her kareye harçtan koyup dört köşesinden birleştirin.
5. Haşlayıp yoğurt ve tereyağlı sosla servis edin.', recipe_is_ai_generated = true where id = 'ccdc53f7-6d6f-408e-841b-f704bd8e49ac';
update public.posts set recipe_text = '1. Un, maya, su ve tuzla hamur yoğurup mayalandırın.
2. Hamuru kayık şeklinde açıp kenarlarını kıvırın.
3. Sucuk ve kaşarı üzerine yayın.
4. Ortasına yumurta kırıp ısıtılmış fırında pişirin.', recipe_is_ai_generated = true where id = '49bdd5bc-3a07-4e04-9217-7cbdb37240f6';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Pirinci suda tamamen yumuşayana kadar kaynatın.
2. Süt, şeker ve vanilyayı ekleyip kıvam alana kadar pişirin.
3. Kaselere paylaştırıp üzeri hafif altın rengi olana kadar fırınlayın.
4. Servisten önce soğutun.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '82202973-2859-4a3f-acdf-eaafcff433c8';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Patlıcanları kızartıp uzunlamasına yarın.
2. Kıymayı soğan, biber ve sarımsakla kavurun.
3. Domates ve salça ekleyip koyu bir iç harç elde edin.
4. Patlıcanları doldurup üzerine domates dilimiyle fırınlayın.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = '28044cae-78bc-468b-85ca-0e48b5a34380';
update public.posts set recipe_text = '1. Salatalığı rendeleyin ya da küçük küpler doğrayın.
2. Sarımsağı ezip dereotunu kıyın.
3. Tuzla yoğurda karıştırın.
4. Zeytinyağı gezdirip servisten önce soğutun.', recipe_is_ai_generated = true where id = 'fc14722a-1567-4a49-aba7-5d646d9af957';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Şeker, su ve limon suyunu kaynatıp şerbeti hazırlayıp soğutun.
2. Tel kadayıfı eritilmiş tereyağıyla harmanlayın.
3. Yarısını tepsiye serip cevizi yayın, kalanla kapatın.
4. Fırında altın rengi olana kadar pişirip soğuk şerbeti gezdirin.', recipe_is_ai_generated = false where id = '65daf5a3-e84a-47c0-bf48-84d9112a465b';
update public.posts set recipe_text = '1. Bamyaların uçlarını incecik kesip limonlu suda biraz bekletin.
2. Soğanı zeytinyağında hafifçe kavurun.
3. Domatesleri rendeleyip ekleyin, birkaç dakika kaynatın.
4. Bamyaları ilave edip kısık ateşte 25 dakika kadar pişirin.
5. Soğuduktan sonra servis edin, sıcağı da fena değil.', recipe_is_ai_generated = true where id = '067bd7f6-1478-48dc-8fc4-031f6db79581';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Eti oda sıcaklığına getirip tuz ve karabiber gezdirin.
2. Kızgın tavada yüksek ateşte her iki tarafını mühürleyin.
3. Tereyağı ve sarımsak ekleyip kendi yağıyla ıslatarak pişirin.
4. Birkaç dakika dinlendirip dilimleyerek servis edin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = '78392cbf-a12a-4f7d-bef3-18205aae024f';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Soğanı zeytinyağında kavurup pirinç, çam fıstığı ve baharatları ekleyin.
2. Asma yapraklarını harçla doldurup sıkıca sarın.
3. Tencereye sık dizip limon suyu ve su ilave edin.
4. Kısık ateşte 40-45 dakika pişirip soğuduktan sonra servis edin.', recipe_is_ai_generated = false where id = '09b17fda-ec08-4c9b-905b-7677a226845d';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Makarnayı tuzlu suda diri kalacak şekilde haşlayın.
2. Sarımsağı soteleyip salça ve domatesi ekleyin.
3. Sos kıvamına gelince süzülmüş makarnayla karıştırın.
4. Rendelenmiş kaşar serperek sıcak servis edin.', recipe_is_ai_generated = false where id = '8413de7f-7c0b-44c3-91fe-374f85fa7a8a';
update public.posts set recipe_text = '1. Soğanı tereyağında kavurup kabak ve patatesi ekleyin.
2. Üzerini geçecek kadar sıcak su ekleyip sebzeler yumuşayana kadar pişirin.
3. Blenderdan geçirip sütü ilave edin.
4. Bir taşım kaynatıp zeytinyağı gezdirerek servis edin.', recipe_is_ai_generated = true where id = 'db76f843-adfa-43f3-872f-ac55493c95d1';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Bamyaların saplarını temizleyip limonlu suyla ovarak yıkayın.
2. Zeytinyağında soğanı pembeleşene kadar kavurun.
3. Rendelenmiş domates ve bamyaları ekleyip 25-30 dakika kısık ateşte pişirin.
4. Ilık ya da soğuk servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = 'ea06cb38-a692-4b7d-9afa-469910e702d5';
update public.posts set recipe_text = '1. Dana kuşbaşıyı yüksek ateşte rengi dönene kadar kavurun.
2. Salçayı ekleyip domates ve sarımsağı ilave edin.
3. Üzerini geçecek kadar su ekleyip kapalı kapak altında 1 saat pişirin.
4. Patates ve biberi ekleyip 20 dakika daha pişirin.', recipe_is_ai_generated = true where id = '74b62c8a-cfbf-4532-8947-835d9ace3225';
update public.posts set recipe_text = 'Bende şöyle oldu:
1. Tereyağlı yufka katmanlarının arasına kıyılmış ceviz serperek dizin.
2. Fırınlamadan önce dilim şeklinde kesin.
3. Altın rengi ve çıtır olana kadar fırınlayın.
4. Sıcak baklavaya soğuk limonlu şerbeti gezdirip çekmesini bekleyin.
Denerseniz nasıl olduğunu yazın bana.', recipe_is_ai_generated = false where id = '653f6b0f-8151-4968-a51d-99e973168d47';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Etleri ayrı ayrı marine edip şişlere dizin.
2. Izgarayı iyice kızdırın.
3. Etleri ve sebzeleri çevirerek eşit pişene kadar közleyin.
4. Sıcak ekmekle tek tabakta servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = 'bb561892-4ee8-49dc-9226-55a6d613a30a';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Cezveye soğuk su, kahve ve istediğiniz kadar şeker ekleyip karıştırın.
2. Kısık ateşte, karıştırmadan yavaşça ısıtın.
3. Köpük kabarınca ocaktan alıp köpüğü fincana paylaştırın.
4. Cezveyi tekrar ocağa koyup son bir kaynatmayla fincana boşaltın.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = '72188c97-a4e0-4737-bf52-a8894737aed3';
update public.posts set recipe_text = '1. Ispanağı soğanla hafifçe soteleyip suyunu süzün.
2. Peynir ve bir yumurtayla karıştırıp harcı hazırlayın.
3. Yufkaları tereyağlı tepsiye dizip arasına harcı serpin.
4. Üzerine yumurta sürüp fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = true where id = 'd5c8af8a-7c5f-41f6-8e34-e6505d38a073';
update public.posts set recipe_text = '1. Un, yumurta ve suyla yufka hamuru hazırlayıp ince açın.
2. Yufkaları tuzlu suda kısaca haşlayıp soğuk suya alın.
3. Tereyağlı tepsiye dizip arasına peynir-maydanoz harcını serpin.
4. Süt gezdirip fırında altın rengi olana kadar pişirin.', recipe_is_ai_generated = true where id = 'd8ad2c68-050a-43cf-a275-46d73e23ed72';
update public.posts set recipe_text = '1. Yufkaları eritilmiş tereyağıyla tek tek yağlayıp tepside üst üste dizin.
2. Aralarına dövülmüş cevizi serpiştirin.
3. Baklavayı dilimleyip kızarana kadar fırınlayın.
4. Şekeri suyla kaynatıp limon damlatarak şerbet hazırlayın.
5. Sıcak baklavanın üzerine soğuk şerbeti gezdirin.', recipe_is_ai_generated = true where id = '3f5e574f-0d2b-4857-a680-ef9213b1b9d8';
update public.posts set recipe_text = '1. Haşlanmış kuru fasulyeyi süzüp bir kaba alın.
2. İnce doğranmış soğan, domates ve maydanozu ekleyin.
3. Zeytinyağı ve limon suyuyla harmanlayın.
4. Haşlanmış yumurta dilimleriyle süsleyerek servis edin.', recipe_is_ai_generated = true where id = 'e388c9a6-b8fd-492f-b14e-314078bc8389';
update public.posts set recipe_text = '1. Beyaz peyniri ezip maydanozla karıştırın.
2. Yufkaları şerit kesip bir ucuna harçtan koyarak sarın.
3. Uçlarını çırpılmış yumurtayla yapıştırın.
4. Kızgın yağda altın rengi olana kadar kızartıp sıcak servis edin.', recipe_is_ai_generated = true where id = '249fbe35-06f0-464d-87e4-0250c4922779';
update public.posts set recipe_text = '1. Un, maya, şeker ve ılık suyla hamur yoğurup mayalandırın.
2. İnce uzun şeritler haline getirip ikişer ikişer bükerek halka verin.
3. Pekmez şerbetine batırıp fırın tepsisine dizin.
4. Isıtılmış fırında altın rengi ve çıtır olana kadar pişirin.', recipe_is_ai_generated = true where id = '74814b28-b503-42b6-80d4-3d59d3cec9a9';
update public.posts set recipe_text = '1. Bir tencere suyu kaynatıp içine sirke ekleyin.
2. Yumurtaları kırıp kaynar suda pıhtılaşana kadar pişirin.
3. Yoğurdu sarımsakla iyice karıştırın.
4. Tereyağını eritip pul biberle kızdırın.
5. Yumurtaları yoğurdun üzerine alıp acılı yağı gezdirin.', recipe_is_ai_generated = true where id = 'baa15232-f257-4bae-b117-ffccad52b618';
update public.posts set recipe_text = '1. Suyu kaynatıp içine biraz sirke ekleyin.
2. Yumurtayı kırıp kaynar suda 3 dakika pişirin.
3. Yoğurdu sarımsakla çırpın.
4. Tereyağını eritip pul biberle kavurun.
5. Yumurtayı yoğurdun üzerine alıp acılı tereyağını gezdirin.', recipe_is_ai_generated = true where id = '38833fd3-9262-4774-8784-49252209fdab';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Fırını 200 dereceye ısıtıp filetoları fırın kağıtlı tepsiye dizin.
2. Ezilmiş sarımsak, zeytinyağı ve limon suyunu karıştırıp üzerine gezdirin.
3. Balık kolayca dağılana kadar 15-18 dakika fırınlayın.
4. Maydanoz ve limon dilimiyle servis edin.', recipe_is_ai_generated = false where id = '26236c75-64ca-4ce5-a02d-7f267bef2fa8';
update public.posts set recipe_text = '1. Elmaların çekirdek kısmını oyarak çıkarın.
2. Ceviz, bal ve tarçını karıştırıp içlerine doldurun.
3. Üzerine küçük tereyağı parçaları koyup fırın kabına dizin.
4. Elmalar yumuşayana kadar 25-30 dakika pişirip sıcak servis edin.', recipe_is_ai_generated = true where id = '46f26ae5-3b6e-4c85-84cd-409e2c02c9c3';
update public.posts set recipe_text = '1. Domates, salatalık ve yeşil biberi küp küp doğrayın.
2. Soğanı ince yarım ay şeklinde kesin.
3. Maydanozu ilave edip hepsini bir kapta karıştırın.
4. Zeytinyağı ve limonla tatlandırıp hemen servis edin.', recipe_is_ai_generated = true where id = '0a9bfd70-bbec-42f3-956a-c68c95a5621c';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Patatesleri haşlayıp soğuduktan sonra küp doğrayın.
2. Yumurtaları haşlayıp küçük parçalar doğrayın.
3. Soğan ve dereotunu ekleyin.
4. Mayonezle harmanlayıp soğuk servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '9880a0c6-37e2-436d-b1d5-0f88a1581f6a';
update public.posts set recipe_text = '1. Tüm sebzeleri iri parçalar halinde doğrayın.
2. Zeytinyağı ve sarımsakla bir güveç kabına dizin.
3. Kapağını kapatıp ara sıra karıştırarak kısık ateşte pişirin.
4. Sıcak ya da oda sıcaklığında servis edin.', recipe_is_ai_generated = true where id = 'dcedd17e-ab81-4ac5-b9ed-658fa5f460f5';
update public.posts set recipe_text = '1. Unu maya ve suyla yoğurup mayalanmaya bırakın.
2. Hamuru parçalayıp ince uzun şeritler açın, ikişer ikişer burun.
3. Pekmez ve suyu karıştırıp şerbet hazırlayın, halkaları bu şerbete batırın.
4. Fırında altın rengi alana kadar pişirin.', recipe_is_ai_generated = true where id = '4ee392ec-429b-4bdc-9bae-ef57a6189e2f';
update public.posts set recipe_text = '1. Biberlerin kapaklarını kesip içlerini oyun.
2. Kıyma, pirinç, doğranmış soğan ve salçayı karıştırıp iç harcı hazırlayın.
3. Harcı biberlere doldurup tencereye dizin.
4. Üzerini geçecek kadar su ekleyip pirinç yumuşayana kadar pişirin.', recipe_is_ai_generated = true where id = '28006930-f156-47a1-97e5-5ca505bce03b';
update public.posts set recipe_text = '1. Sütü şeker ve irmikle koyulaşana kadar pişirin.
2. Karışımı yağlanmış bir tepsiye dökün.
3. Tepsiyi ocak üzerinde altı hafif karamelize olana kadar pişirin.
4. Soğuyunca dilimleyip rulo şeklinde sararak servis edin.', recipe_is_ai_generated = true where id = '29c26c0b-40aa-401b-85fc-ccd2dd0671ed';
update public.posts set recipe_text = '1. Bitter çikolatayı benmari usulü eritin.
2. Krema ve kakaoyu çırpıp eritilmiş çikolatayla karıştırın.
3. Yumurta sarılarını şekerle çırpıp karışıma ekleyin.
4. Kaselere paylaştırıp en az 2 saat buzdolabında dinlendirin.', recipe_is_ai_generated = true where id = 'dde6895b-e21c-46c8-bed9-c5ef8ab438be';
update public.posts set recipe_text = '1. Kıymayı tuz ve karabiberle yoğurup köfteler haline getirin.
2. Köfteleri her iki yüzü mühürlenene kadar pişirip üzerine kaşarı eritin.
3. Ekmekleri kızartıp içine ketçap ve mayonez sürün.
4. Marul, domates ve köfteyi ekmeğin arasına yerleştirip servis edin.', recipe_is_ai_generated = true where id = 'b0a6bc7b-bf1b-44d4-8c26-240504d13289';
update public.posts set recipe_text = '1. Semizotunu ayıklayıp yıkayın ve iri doğrayın.
2. Zeytinyağında pirinci kavurup semizotunu ekleyin, kendi suyunda pişirin.
3. Yoğurdu sarımsakla karıştırın.
4. Soğuyan semizotunun üzerine sarımsaklı yoğurdu gezdirerek servis edin.', recipe_is_ai_generated = true where id = 'c9071f57-1173-43bc-a8e8-cc44e32035b8';
update public.posts set recipe_text = 'Bende şöyle oldu:
1. Haşlanmış nohudu tahin, limon suyu ve sarımsakla blenderdan geçirin.
2. Kıvam alana kadar yavaşça soğuk su ekleyin.
3. Kimyon ve tuzla tatlandırın.
4. Zeytinyağı gezdirerek servis edin.', recipe_is_ai_generated = false where id = '30d58e61-88b9-41ee-8dc9-a261e6ead75e';
update public.posts set recipe_text = '1. Şeker, su ve limon suyunu kaynatıp şerbeti hazırlayıp soğutun.
2. Yufkayı didikleyip eritilmiş tereyağıyla harmanlayın.
3. Tepsiye yarısını serip peyniri koyup kalan yufkayla kapatın.
4. İki tarafı altın rengi olana kadar pişirip soğuk şerbeti gezdirin, cevizle servis edin.', recipe_is_ai_generated = true where id = '09ae3be5-8830-478c-ac4f-5036d965c65c';
update public.posts set recipe_text = '1. Eti sıcak yağda kısa sürede mühürleyin.
2. Doğranmış soğan ve sarımsağı ekleyip kavurun.
3. Salça ve domatesi ilave edip birkaç dakika pişirin.
4. Patates ve biberi ekleyip üzerini geçecek kadar su koyun.
5. Kısık ateşte et yumuşayana kadar güveçte pişirin.', recipe_is_ai_generated = true where id = 'fb4f6f95-d942-44a0-a664-89135d7ee72c';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Beyaz peyniri maydanozla ezip harcı hazırlıyorum.
2. Yufkayı üçgen şeritler halinde kesip ucuna harçtan koyuyorum.
3. Sarıp ucunu yumurtayla yapıştırıyorum.
4. Kızgın yağda her iki tarafını da kızartıyorum.
Sıcakken yiyin, soğuyunca aynı tadı vermiyor.', recipe_is_ai_generated = false where id = '99d979a1-67e1-45e3-bf73-62ce77962382';
update public.posts set recipe_text = '1. Salep tozunu bir miktar soğuk sütle ezip pürüzsüz hale getirin.
2. Kalan sütü şekerle birlikte ısıtın.
3. Salep karışımını yavaşça ekleyip sürekli karıştırın.
4. Kıvam alana kadar kısık ateşte pişirmeye devam edin.
5. Bardaklara döküp üzerine tarçın serpin.', recipe_is_ai_generated = true where id = 'ade10482-71f4-489b-8934-09df244cc71b';
update public.posts set recipe_text = '1. Domates ve soğanı iri parçalar halinde doğrayın.
2. Ceviz ve maydanozu kabaca kıyın.
3. Zeytinyağı ve pul biberle birleştirin.
4. 5 dakika dinlendirip servis edin.', recipe_is_ai_generated = true where id = '0ecfe9be-8061-4574-87d8-4200eaa27dd6';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Etleri ayrı ayrı marine edip şişlere dizin.
2. Izgarayı iyice kızdırın.
3. Etleri ve sebzeleri çevirerek eşit pişene kadar közleyin.
4. Sıcak ekmekle tek tabakta servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = 'a1a7766b-a7a5-48fe-bb0e-a5e5a0d25278';
update public.posts set recipe_text = '1. Soğanı zeytinyağında kavurup pirinç, çam fıstığı ve baharatları ekleyin.
2. Asma yapraklarını harçla doldurup sıkıca sarın.
3. Tencereye sık dizip limon suyu ve su ilave edin.
4. Kısık ateşte 40-45 dakika pişirip soğuduktan sonra servis edin.', recipe_is_ai_generated = true where id = '7a20fdb3-89f6-49c8-85f9-c02f5115a29e';
update public.posts set recipe_text = '1. İnce bulguru sıcak suda 15 dakika bekletip kabartın.
2. İki salçayı ve zeytinyağını ekleyip iyice yoğurun.
3. Küçük doğranmış domates, salatalık ve maydanozu karıştırın.
4. Limon suyunu gezdirip soğuk servis edin.', recipe_is_ai_generated = true where id = '3fa4aa11-653a-4867-8188-72fc0e952cae';
update public.posts set recipe_text = '1. Tavuğu zeytinyağı, limon, sarımsak ve kırmızı toz biberle marine edin.
2. En az 20 dakika dinlendirin.
3. Orta-yüksek ateşte ızgarada ya da tavada pişirin.
4. Dilimlemeden önce birkaç dakika dinlendirin.', recipe_is_ai_generated = true where id = '37cdcaca-095a-4f3b-8198-15168cfcd7af';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Balık filetolarını zeytinyağı ve limon suyuyla marine edin.
2. Biber ve kabağı dilimleyip zeytinyağıyla harmanlayın.
3. Izgarada balığı ve sebzeleri çevirerek pişirin.
4. Limon dilimiyle sıcak servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = '33c52cbb-4d7d-49e5-afcf-e62a8ce3154c';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Kıymayı soğan, pul biber ve tuzla iyice yoğurup dinlendirin.
2. Harcı şişlere yassı ve uzun şekilde sarın.
3. Közde çevirerek pişirin, domates ve biberi de yanında közleyin.
4. Sıcak ekmek ve maydanozla servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = 'ecf5bb36-887c-4f16-acb9-96c5b0b27ad0';
update public.posts set recipe_text = '1. Bulguru sıcak suyla ıslatıp kabarmasını bekleyin.
2. Salça ve biber salçasını bulgurla iyice yoğurun.
3. Domates ve salatalığı ince doğrayıp ekleyin.
4. Maydanoz, zeytinyağı ve limonu ekleyip son kez karıştırın.
5. Buzdolabında dinlendirip soğuk servis edin.', recipe_is_ai_generated = true where id = '09b9a08d-a710-45fe-8ae9-a3bd8b6ed3ed';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Soğanı zeytinyağında kavurup pirinç, çam fıstığı ve baharatları ekleyin.
2. Asma yapraklarını harçla doldurup sıkıca sarın.
3. Tencereye sık dizip limon suyu ve su ilave edin.
4. Kısık ateşte 40-45 dakika pişirip soğuduktan sonra servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '59f71b8a-2447-48d9-882a-01589b5ae528';
update public.posts set recipe_text = 'Bende şöyle oldu:
1. Tereyağında soğan ve biberi yumuşatın.
2. Rendelenmiş domatesi ekleyip birkaç dakika pişirin.
3. Bulguru kavurup sıcak su ilave edin.
4. Suyunu çekene kadar pişirip demlendirerek servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '226d4c25-6017-40d4-8535-b0ce598a2922';
update public.posts set recipe_text = 'Ben böyle yapıyorum:
1. Tavuk butlarını küp doğrayıp baharatlayın.
2. Sıcak yağda mühürleyip kenara alın.
3. Soğan ve biberleri soteleyip domatesi ekleyin.
4. Tavuğu geri ekleyip kısık ateşte pişene kadar pişirin.', recipe_is_ai_generated = false where id = '69f2a905-d148-4ff7-a3f3-95b4c6288702';
update public.posts set recipe_text = '1. Patatesleri haşlayıp soğuduktan sonra küp doğrayın.
2. Yumurtaları haşlayıp küçük parçalar doğrayın.
3. Soğan ve dereotunu ekleyin.
4. Mayonezle harmanlayıp soğuk servis edin.', recipe_is_ai_generated = true where id = '2bcb4e70-dac1-488b-8ca9-bdff39269053';
update public.posts set recipe_text = 'Şöyle hallettim:
1. Tereyağında çam fıstığını hafif kavurup kenara alın.
2. Aynı yağda irmiği mis gibi koku yayılana kadar kavurun.
3. Sıcak süt ve şekeri irmiğin üzerine dökün, karıştırmadan demlendirin.
4. Karıştırıp çam fıstığı serperek sıcak servis edin.
Afiyet olsun!', recipe_is_ai_generated = false where id = '535b7cd6-ca35-4278-9210-a524946f2edd';
update public.posts set recipe_text = '1. Eti kuru tavada suyunu çekene kadar kavurun.
2. Tereyağını ekleyip kendi yağında kızartın.
3. Soğanı ekleyip yumuşayana kadar kavurun.
4. Karabiberle tatlandırıp sıcak servis edin.', recipe_is_ai_generated = true where id = '787af8e8-9aec-4905-ba64-1fc25bf04231';
update public.posts set recipe_text = '1. Elmaların çekirdek kısmını oyun.
2. İçine kıyılmış ceviz, tarçın ve bal doldurun.
3. Üzerine küçük bir parça tereyağı koyun.
4. Fırın kabına dizip 180 derecede elmalar yumuşayana kadar pişirin.', recipe_is_ai_generated = true where id = 'd7be3123-d644-4503-b605-a5e9dc0ccdbd';
update public.posts set recipe_text = '1. Soğanı zeytinyağında yumuşayana kadar kavurun.
2. Rendelenmiş havucu ekleyip birkaç dakika pişirin.
3. Salçayı ilave edip kavurmaya devam edin.
4. Haşlanmış nohutu ve biraz suyu ekleyip 15 dakika pişirin.
5. Ilık ya da soğuk servis edilebilir.', recipe_is_ai_generated = true where id = '1646d290-2dbc-45b6-be51-b75c92d3bb54';
update public.posts set recipe_text = '1. Kuşbaşı eti sıcak tavada kısa sürede mühürleyin.
2. Ekmekleri dilimleyip tabağın tabanına yayın.
3. Salçalı domates sosunu ayrı kaynatın.
4. Eti ekmeklerin üstüne koyup sosu üzerine dökün.
5. Yoğurt ve kızgın tereyağıyla tamamlayıp sıcak servis edin.', recipe_is_ai_generated = true where id = '781acadb-82b4-4bc3-9793-fd76cabdf833';
update public.posts set recipe_text = '1. Patlıcanları soyup uzunlamasına kızartın.
2. Kıymayı soğan, biber ve sarımsakla kavurun.
3. Domates ve salçayı ekleyip harcı koyulaştırın.
4. Patlıcanları yarıp içine harcı doldurun.
5. Üzerine domates dilimi koyup fırında pişirin.', recipe_is_ai_generated = true where id = '2904ed85-3e2d-4249-947c-a12a06de0cd0';
update public.posts set recipe_text = 'Benim yaptığım şekli:
1. Makarnayı tuzlu suda diri kalacak şekilde haşlayın.
2. Sarımsağı soteleyip salça ve domatesi ekleyin.
3. Sos kıvamına gelince süzülmüş makarnayla karıştırın.
4. Rendelenmiş kaşar serperek sıcak servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '9500be3e-1b26-4330-9a92-5bc6c9f49aec';
update public.posts set recipe_text = '1. Haşlanmış beyaz fasulyeyi bir kaba alın.
2. Soğanı ince doğrayıp tuzla ovun, acılığını azaltın.
3. Domates ve maydanozu ekleyip karıştırın.
4. Zeytinyağı ve limonla tatlandırın.
5. Haşlanmış yumurtayla süsleyip servis edin.', recipe_is_ai_generated = true where id = '4dafb2ad-c8f4-4dac-a50d-6f085b49f050';
update public.posts set recipe_text = '1. Şeker, su ve limon suyunu kaynatıp şerbeti hazırlayıp soğutun.
2. Tel kadayıfı eritilmiş tereyağıyla harmanlayın.
3. Yarısını tepsiye serip cevizi yayın, kalanla kapatın.
4. Fırında altın rengi olana kadar pişirip soğuk şerbeti gezdirin.', recipe_is_ai_generated = true where id = 'fc0097fb-e11d-4a92-974c-97856b18a2cf';
update public.posts set recipe_text = 'Ben genelde şöyle yapıyorum:
1. Mercimekleri yıkayıp sebzeleri doğrayın.
2. Soğan ve havucu tereyağında kavurup salçayı ekleyin.
3. Mercimek, patates ve suyu ekleyip 20 dakika pişirin.
4. Blenderdan geçirip kimyon ve limonla servis edin.
Bende böyle güzel oldu, umarım sizde de olur.', recipe_is_ai_generated = false where id = '39f95bcf-e8cd-4eb0-bcb2-2cc933f01fae';
update public.posts set recipe_text = '1. Kıymayı tuz ve karabiberle yoğurup köfte şekli verin.
2. Köfteleri sıcak tavada iki tarafını da mühürleyin.
3. Ekmekleri hafifçe kızartıp ketçap ve mayonez sürün.
4. Marul, domates ve kaşarı ekleyip köfteyi üzerine yerleştirin.
5. Ekmeğin üst kısmıyla kapatıp servis edin.', recipe_is_ai_generated = true where id = 'c8accce3-ad2e-4ece-bedd-7006739a6bb9';
update public.posts set recipe_text = '1. Semizotunu ayıklayıp yıkayın ve iri doğrayın.
2. Zeytinyağında pirinci kavurup semizotunu ekleyin, kendi suyunda pişirin.
3. Yoğurdu sarımsakla karıştırın.
4. Soğuyan semizotunun üzerine sarımsaklı yoğurdu gezdirerek servis edin.
Ellerinize sağlık demeyi unutmayın :)', recipe_is_ai_generated = false where id = '1056a768-591b-4d67-a14c-82f4e495f438';
